// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/model/v1/config.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeleopRosStreamConfigurationMode int32

const (
	TeleopRosStreamConfigurationMode_COMMAND TeleopRosStreamConfigurationMode = 0
	TeleopRosStreamConfigurationMode_OBSERVE TeleopRosStreamConfigurationMode = 1
)

var TeleopRosStreamConfigurationMode_name = map[int32]string{
	0: "COMMAND",
	1: "OBSERVE",
}

var TeleopRosStreamConfigurationMode_value = map[string]int32{
	"COMMAND": 0,
	"OBSERVE": 1,
}

func (x TeleopRosStreamConfigurationMode) String() string {
	return proto.EnumName(TeleopRosStreamConfigurationMode_name, int32(x))
}

func (TeleopRosStreamConfigurationMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{0}
}

type FileFormat int32

const (
	FileFormat_PLAIN_TEXT FileFormat = 0
	FileFormat_JSON       FileFormat = 1
)

var FileFormat_name = map[int32]string{
	0: "PLAIN_TEXT",
	1: "JSON",
}

var FileFormat_value = map[string]int32{
	"PLAIN_TEXT": 0,
	"JSON":       1,
}

func (x FileFormat) String() string {
	return proto.EnumName(FileFormat_name, int32(x))
}

func (FileFormat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{1}
}

type FileType int32

const (
	FileType_FILE        FileType = 0
	FileType_IMAGE       FileType = 1
	FileType_POINT_CLOUD FileType = 4
	FileType_VIDEO       FileType = 5
)

var FileType_name = map[int32]string{
	0: "FILE",
	1: "IMAGE",
	4: "POINT_CLOUD",
	5: "VIDEO",
}

var FileType_value = map[string]int32{
	"FILE":        0,
	"IMAGE":       1,
	"POINT_CLOUD": 4,
	"VIDEO":       5,
}

func (x FileType) String() string {
	return proto.EnumName(FileType_name, int32(x))
}

func (FileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{2}
}

type AgentConfigurationStore struct {
	AgentVersion         string              `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Configuration        *AgentConfiguration `protobuf:"bytes,2,opt,name=configuration,proto3" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AgentConfigurationStore) Reset()         { *m = AgentConfigurationStore{} }
func (m *AgentConfigurationStore) String() string { return proto.CompactTextString(m) }
func (*AgentConfigurationStore) ProtoMessage()    {}
func (*AgentConfigurationStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{0}
}

func (m *AgentConfigurationStore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentConfigurationStore.Unmarshal(m, b)
}
func (m *AgentConfigurationStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentConfigurationStore.Marshal(b, m, deterministic)
}
func (m *AgentConfigurationStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentConfigurationStore.Merge(m, src)
}
func (m *AgentConfigurationStore) XXX_Size() int {
	return xxx_messageInfo_AgentConfigurationStore.Size(m)
}
func (m *AgentConfigurationStore) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentConfigurationStore.DiscardUnknown(m)
}

var xxx_messageInfo_AgentConfigurationStore proto.InternalMessageInfo

func (m *AgentConfigurationStore) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

func (m *AgentConfigurationStore) GetConfiguration() *AgentConfiguration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

type AgentConfiguration struct {
	Id                   string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Document             *AgentConfigurationDocument `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AgentConfiguration) Reset()         { *m = AgentConfiguration{} }
func (m *AgentConfiguration) String() string { return proto.CompactTextString(m) }
func (*AgentConfiguration) ProtoMessage()    {}
func (*AgentConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{1}
}

func (m *AgentConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentConfiguration.Unmarshal(m, b)
}
func (m *AgentConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentConfiguration.Marshal(b, m, deterministic)
}
func (m *AgentConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentConfiguration.Merge(m, src)
}
func (m *AgentConfiguration) XXX_Size() int {
	return xxx_messageInfo_AgentConfiguration.Size(m)
}
func (m *AgentConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_AgentConfiguration proto.InternalMessageInfo

func (m *AgentConfiguration) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AgentConfiguration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentConfiguration) GetDocument() *AgentConfigurationDocument {
	if m != nil {
		return m.Document
	}
	return nil
}

type AgentConfigurationDocument struct {
	Version              int64                        `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Tags                 map[string]string            `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Telemetry            *TelemetryConfiguration      `protobuf:"bytes,3,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	Resources            *ResourcesConfiguration      `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	Application          *ApplicationConfiguration    `protobuf:"bytes,5,opt,name=application,proto3" json:"application,omitempty"`
	Teleop               *TeleopConfiguration         `protobuf:"bytes,6,opt,name=teleop,proto3" json:"teleop,omitempty"`
	PortForwarding       *PortForwardingConfiguration `protobuf:"bytes,7,opt,name=port_forwarding,json=portForwarding,proto3" json:"port_forwarding,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *AgentConfigurationDocument) Reset()         { *m = AgentConfigurationDocument{} }
func (m *AgentConfigurationDocument) String() string { return proto.CompactTextString(m) }
func (*AgentConfigurationDocument) ProtoMessage()    {}
func (*AgentConfigurationDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{2}
}

func (m *AgentConfigurationDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentConfigurationDocument.Unmarshal(m, b)
}
func (m *AgentConfigurationDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentConfigurationDocument.Marshal(b, m, deterministic)
}
func (m *AgentConfigurationDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentConfigurationDocument.Merge(m, src)
}
func (m *AgentConfigurationDocument) XXX_Size() int {
	return xxx_messageInfo_AgentConfigurationDocument.Size(m)
}
func (m *AgentConfigurationDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentConfigurationDocument.DiscardUnknown(m)
}

var xxx_messageInfo_AgentConfigurationDocument proto.InternalMessageInfo

func (m *AgentConfigurationDocument) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AgentConfigurationDocument) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *AgentConfigurationDocument) GetTelemetry() *TelemetryConfiguration {
	if m != nil {
		return m.Telemetry
	}
	return nil
}

func (m *AgentConfigurationDocument) GetResources() *ResourcesConfiguration {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *AgentConfigurationDocument) GetApplication() *ApplicationConfiguration {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *AgentConfigurationDocument) GetTeleop() *TeleopConfiguration {
	if m != nil {
		return m.Teleop
	}
	return nil
}

func (m *AgentConfigurationDocument) GetPortForwarding() *PortForwardingConfiguration {
	if m != nil {
		return m.PortForwarding
	}
	return nil
}

type TeleopConfiguration struct {
	RosStreams           []*TeleopRosStreamConfiguration `protobuf:"bytes,1,rep,name=ros_streams,json=rosStreams,proto3" json:"ros_streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *TeleopConfiguration) Reset()         { *m = TeleopConfiguration{} }
func (m *TeleopConfiguration) String() string { return proto.CompactTextString(m) }
func (*TeleopConfiguration) ProtoMessage()    {}
func (*TeleopConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{3}
}

func (m *TeleopConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeleopConfiguration.Unmarshal(m, b)
}
func (m *TeleopConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeleopConfiguration.Marshal(b, m, deterministic)
}
func (m *TeleopConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeleopConfiguration.Merge(m, src)
}
func (m *TeleopConfiguration) XXX_Size() int {
	return xxx_messageInfo_TeleopConfiguration.Size(m)
}
func (m *TeleopConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_TeleopConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_TeleopConfiguration proto.InternalMessageInfo

func (m *TeleopConfiguration) GetRosStreams() []*TeleopRosStreamConfiguration {
	if m != nil {
		return m.RosStreams
	}
	return nil
}

type PortForwardingConfiguration struct {
	Enabled              *wrappers.BoolValue `protobuf:"bytes,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PortForwardingConfiguration) Reset()         { *m = PortForwardingConfiguration{} }
func (m *PortForwardingConfiguration) String() string { return proto.CompactTextString(m) }
func (*PortForwardingConfiguration) ProtoMessage()    {}
func (*PortForwardingConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{4}
}

func (m *PortForwardingConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortForwardingConfiguration.Unmarshal(m, b)
}
func (m *PortForwardingConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortForwardingConfiguration.Marshal(b, m, deterministic)
}
func (m *PortForwardingConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortForwardingConfiguration.Merge(m, src)
}
func (m *PortForwardingConfiguration) XXX_Size() int {
	return xxx_messageInfo_PortForwardingConfiguration.Size(m)
}
func (m *PortForwardingConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_PortForwardingConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_PortForwardingConfiguration proto.InternalMessageInfo

func (m *PortForwardingConfiguration) GetEnabled() *wrappers.BoolValue {
	if m != nil {
		return m.Enabled
	}
	return nil
}

type TeleopRosStreamConfiguration struct {
	TopicName            string                           `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	TopicType            ROSTopicType                     `protobuf:"varint,2,opt,name=topic_type,json=topicType,proto3,enum=v1.model.ROSTopicType" json:"topic_type,omitempty"`
	Mode                 TeleopRosStreamConfigurationMode `protobuf:"varint,3,opt,name=mode,proto3,enum=v1.model.TeleopRosStreamConfigurationMode" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *TeleopRosStreamConfiguration) Reset()         { *m = TeleopRosStreamConfiguration{} }
func (m *TeleopRosStreamConfiguration) String() string { return proto.CompactTextString(m) }
func (*TeleopRosStreamConfiguration) ProtoMessage()    {}
func (*TeleopRosStreamConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{5}
}

func (m *TeleopRosStreamConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeleopRosStreamConfiguration.Unmarshal(m, b)
}
func (m *TeleopRosStreamConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeleopRosStreamConfiguration.Marshal(b, m, deterministic)
}
func (m *TeleopRosStreamConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeleopRosStreamConfiguration.Merge(m, src)
}
func (m *TeleopRosStreamConfiguration) XXX_Size() int {
	return xxx_messageInfo_TeleopRosStreamConfiguration.Size(m)
}
func (m *TeleopRosStreamConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_TeleopRosStreamConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_TeleopRosStreamConfiguration proto.InternalMessageInfo

func (m *TeleopRosStreamConfiguration) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *TeleopRosStreamConfiguration) GetTopicType() ROSTopicType {
	if m != nil {
		return m.TopicType
	}
	return ROSTopicType_UNKNOWN
}

func (m *TeleopRosStreamConfiguration) GetMode() TeleopRosStreamConfigurationMode {
	if m != nil {
		return m.Mode
	}
	return TeleopRosStreamConfigurationMode_COMMAND
}

type TelemetryConfiguration struct {
	Streams              []*StreamConfiguration `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	Ros                  *ROSConfiguration      `protobuf:"bytes,2,opt,name=ros,proto3" json:"ros,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TelemetryConfiguration) Reset()         { *m = TelemetryConfiguration{} }
func (m *TelemetryConfiguration) String() string { return proto.CompactTextString(m) }
func (*TelemetryConfiguration) ProtoMessage()    {}
func (*TelemetryConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{6}
}

func (m *TelemetryConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryConfiguration.Unmarshal(m, b)
}
func (m *TelemetryConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryConfiguration.Marshal(b, m, deterministic)
}
func (m *TelemetryConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryConfiguration.Merge(m, src)
}
func (m *TelemetryConfiguration) XXX_Size() int {
	return xxx_messageInfo_TelemetryConfiguration.Size(m)
}
func (m *TelemetryConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryConfiguration proto.InternalMessageInfo

func (m *TelemetryConfiguration) GetStreams() []*StreamConfiguration {
	if m != nil {
		return m.Streams
	}
	return nil
}

func (m *TelemetryConfiguration) GetRos() *ROSConfiguration {
	if m != nil {
		return m.Ros
	}
	return nil
}

type ApplicationConfiguration struct {
	ConfigurationMap     map[string]string `protobuf:"bytes,1,rep,name=configuration_map,json=configurationMap,proto3" json:"configuration_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ApplicationConfiguration) Reset()         { *m = ApplicationConfiguration{} }
func (m *ApplicationConfiguration) String() string { return proto.CompactTextString(m) }
func (*ApplicationConfiguration) ProtoMessage()    {}
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{7}
}

func (m *ApplicationConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationConfiguration.Unmarshal(m, b)
}
func (m *ApplicationConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationConfiguration.Marshal(b, m, deterministic)
}
func (m *ApplicationConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationConfiguration.Merge(m, src)
}
func (m *ApplicationConfiguration) XXX_Size() int {
	return xxx_messageInfo_ApplicationConfiguration.Size(m)
}
func (m *ApplicationConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationConfiguration proto.InternalMessageInfo

func (m *ApplicationConfiguration) GetConfigurationMap() map[string]string {
	if m != nil {
		return m.ConfigurationMap
	}
	return nil
}

type ResourcesConfiguration struct {
	Disk                 *DiskConfiguration    `protobuf:"bytes,1,opt,name=disk,proto3" json:"disk,omitempty"`
	StreamThrottleHz     *wrappers.DoubleValue `protobuf:"bytes,2,opt,name=stream_throttle_hz,json=streamThrottleHz,proto3" json:"stream_throttle_hz,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ResourcesConfiguration) Reset()         { *m = ResourcesConfiguration{} }
func (m *ResourcesConfiguration) String() string { return proto.CompactTextString(m) }
func (*ResourcesConfiguration) ProtoMessage()    {}
func (*ResourcesConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{8}
}

func (m *ResourcesConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourcesConfiguration.Unmarshal(m, b)
}
func (m *ResourcesConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourcesConfiguration.Marshal(b, m, deterministic)
}
func (m *ResourcesConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourcesConfiguration.Merge(m, src)
}
func (m *ResourcesConfiguration) XXX_Size() int {
	return xxx_messageInfo_ResourcesConfiguration.Size(m)
}
func (m *ResourcesConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourcesConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ResourcesConfiguration proto.InternalMessageInfo

func (m *ResourcesConfiguration) GetDisk() *DiskConfiguration {
	if m != nil {
		return m.Disk
	}
	return nil
}

func (m *ResourcesConfiguration) GetStreamThrottleHz() *wrappers.DoubleValue {
	if m != nil {
		return m.StreamThrottleHz
	}
	return nil
}

type DiskConfiguration struct {
	BufferSize           int64    `protobuf:"varint,1,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	OnDemandBufferSize   int64    `protobuf:"varint,2,opt,name=on_demand_buffer_size,json=onDemandBufferSize,proto3" json:"on_demand_buffer_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskConfiguration) Reset()         { *m = DiskConfiguration{} }
func (m *DiskConfiguration) String() string { return proto.CompactTextString(m) }
func (*DiskConfiguration) ProtoMessage()    {}
func (*DiskConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{9}
}

func (m *DiskConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskConfiguration.Unmarshal(m, b)
}
func (m *DiskConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskConfiguration.Marshal(b, m, deterministic)
}
func (m *DiskConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskConfiguration.Merge(m, src)
}
func (m *DiskConfiguration) XXX_Size() int {
	return xxx_messageInfo_DiskConfiguration.Size(m)
}
func (m *DiskConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_DiskConfiguration proto.InternalMessageInfo

func (m *DiskConfiguration) GetBufferSize() int64 {
	if m != nil {
		return m.BufferSize
	}
	return 0
}

func (m *DiskConfiguration) GetOnDemandBufferSize() int64 {
	if m != nil {
		return m.OnDemandBufferSize
	}
	return 0
}

type ROSConfiguration struct {
	WorldReferenceFrameId string   `protobuf:"bytes,1,opt,name=world_reference_frame_id,json=worldReferenceFrameId,proto3" json:"world_reference_frame_id,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ROSConfiguration) Reset()         { *m = ROSConfiguration{} }
func (m *ROSConfiguration) String() string { return proto.CompactTextString(m) }
func (*ROSConfiguration) ProtoMessage()    {}
func (*ROSConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{10}
}

func (m *ROSConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ROSConfiguration.Unmarshal(m, b)
}
func (m *ROSConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ROSConfiguration.Marshal(b, m, deterministic)
}
func (m *ROSConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ROSConfiguration.Merge(m, src)
}
func (m *ROSConfiguration) XXX_Size() int {
	return xxx_messageInfo_ROSConfiguration.Size(m)
}
func (m *ROSConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ROSConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ROSConfiguration proto.InternalMessageInfo

func (m *ROSConfiguration) GetWorldReferenceFrameId() string {
	if m != nil {
		return m.WorldReferenceFrameId
	}
	return ""
}

type StreamConfiguration struct {
	Name string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tags map[string]string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Types that are valid to be assigned to Configuration:
	//	*StreamConfiguration_RosTopic
	//	*StreamConfiguration_RosLocalization
	//	*StreamConfiguration_DirectoryWatch
	//	*StreamConfiguration_FileTail
	//	*StreamConfiguration_RosTransformTree
	//	*StreamConfiguration_Custom
	Configuration        isStreamConfiguration_Configuration `protobuf_oneof:"configuration"`
	ThrottleHz           *wrappers.DoubleValue               `protobuf:"bytes,8,opt,name=throttle_hz,json=throttleHz,proto3" json:"throttle_hz,omitempty"`
	Disabled             *wrappers.BoolValue                 `protobuf:"bytes,19,opt,name=disabled,proto3" json:"disabled,omitempty"`
	OnDemand             *wrappers.BoolValue                 `protobuf:"bytes,20,opt,name=on_demand,json=onDemand,proto3" json:"on_demand,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *StreamConfiguration) Reset()         { *m = StreamConfiguration{} }
func (m *StreamConfiguration) String() string { return proto.CompactTextString(m) }
func (*StreamConfiguration) ProtoMessage()    {}
func (*StreamConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{11}
}

func (m *StreamConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamConfiguration.Unmarshal(m, b)
}
func (m *StreamConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamConfiguration.Marshal(b, m, deterministic)
}
func (m *StreamConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamConfiguration.Merge(m, src)
}
func (m *StreamConfiguration) XXX_Size() int {
	return xxx_messageInfo_StreamConfiguration.Size(m)
}
func (m *StreamConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_StreamConfiguration proto.InternalMessageInfo

func (m *StreamConfiguration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StreamConfiguration) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type isStreamConfiguration_Configuration interface {
	isStreamConfiguration_Configuration()
}

type StreamConfiguration_RosTopic struct {
	RosTopic *ROSTopic `protobuf:"bytes,3,opt,name=ros_topic,json=rosTopic,proto3,oneof"`
}

type StreamConfiguration_RosLocalization struct {
	RosLocalization *ROSLocalization `protobuf:"bytes,4,opt,name=ros_localization,json=rosLocalization,proto3,oneof"`
}

type StreamConfiguration_DirectoryWatch struct {
	DirectoryWatch *DirectoryWatch `protobuf:"bytes,5,opt,name=directory_watch,json=directoryWatch,proto3,oneof"`
}

type StreamConfiguration_FileTail struct {
	FileTail *FileTail `protobuf:"bytes,6,opt,name=file_tail,json=fileTail,proto3,oneof"`
}

type StreamConfiguration_RosTransformTree struct {
	RosTransformTree *ROSTransformTree `protobuf:"bytes,7,opt,name=ros_transform_tree,json=rosTransformTree,proto3,oneof"`
}

type StreamConfiguration_Custom struct {
	Custom *Custom `protobuf:"bytes,9,opt,name=custom,proto3,oneof"`
}

func (*StreamConfiguration_RosTopic) isStreamConfiguration_Configuration() {}

func (*StreamConfiguration_RosLocalization) isStreamConfiguration_Configuration() {}

func (*StreamConfiguration_DirectoryWatch) isStreamConfiguration_Configuration() {}

func (*StreamConfiguration_FileTail) isStreamConfiguration_Configuration() {}

func (*StreamConfiguration_RosTransformTree) isStreamConfiguration_Configuration() {}

func (*StreamConfiguration_Custom) isStreamConfiguration_Configuration() {}

func (m *StreamConfiguration) GetConfiguration() isStreamConfiguration_Configuration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

func (m *StreamConfiguration) GetRosTopic() *ROSTopic {
	if x, ok := m.GetConfiguration().(*StreamConfiguration_RosTopic); ok {
		return x.RosTopic
	}
	return nil
}

func (m *StreamConfiguration) GetRosLocalization() *ROSLocalization {
	if x, ok := m.GetConfiguration().(*StreamConfiguration_RosLocalization); ok {
		return x.RosLocalization
	}
	return nil
}

func (m *StreamConfiguration) GetDirectoryWatch() *DirectoryWatch {
	if x, ok := m.GetConfiguration().(*StreamConfiguration_DirectoryWatch); ok {
		return x.DirectoryWatch
	}
	return nil
}

func (m *StreamConfiguration) GetFileTail() *FileTail {
	if x, ok := m.GetConfiguration().(*StreamConfiguration_FileTail); ok {
		return x.FileTail
	}
	return nil
}

func (m *StreamConfiguration) GetRosTransformTree() *ROSTransformTree {
	if x, ok := m.GetConfiguration().(*StreamConfiguration_RosTransformTree); ok {
		return x.RosTransformTree
	}
	return nil
}

func (m *StreamConfiguration) GetCustom() *Custom {
	if x, ok := m.GetConfiguration().(*StreamConfiguration_Custom); ok {
		return x.Custom
	}
	return nil
}

func (m *StreamConfiguration) GetThrottleHz() *wrappers.DoubleValue {
	if m != nil {
		return m.ThrottleHz
	}
	return nil
}

func (m *StreamConfiguration) GetDisabled() *wrappers.BoolValue {
	if m != nil {
		return m.Disabled
	}
	return nil
}

func (m *StreamConfiguration) GetOnDemand() *wrappers.BoolValue {
	if m != nil {
		return m.OnDemand
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamConfiguration) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamConfiguration_RosTopic)(nil),
		(*StreamConfiguration_RosLocalization)(nil),
		(*StreamConfiguration_DirectoryWatch)(nil),
		(*StreamConfiguration_FileTail)(nil),
		(*StreamConfiguration_RosTransformTree)(nil),
		(*StreamConfiguration_Custom)(nil),
	}
}

type Custom struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Custom) Reset()         { *m = Custom{} }
func (m *Custom) String() string { return proto.CompactTextString(m) }
func (*Custom) ProtoMessage()    {}
func (*Custom) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{12}
}

func (m *Custom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Custom.Unmarshal(m, b)
}
func (m *Custom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Custom.Marshal(b, m, deterministic)
}
func (m *Custom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Custom.Merge(m, src)
}
func (m *Custom) XXX_Size() int {
	return xxx_messageInfo_Custom.Size(m)
}
func (m *Custom) XXX_DiscardUnknown() {
	xxx_messageInfo_Custom.DiscardUnknown(m)
}

var xxx_messageInfo_Custom proto.InternalMessageInfo

type DirectoryWatch struct {
	Directory            string   `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	Extension            string   `protobuf:"bytes,2,opt,name=extension,proto3" json:"extension,omitempty"`
	FileType             FileType `protobuf:"varint,3,opt,name=file_type,json=fileType,proto3,enum=v1.model.FileType" json:"file_type,omitempty"`
	RemoteAgent          bool     `protobuf:"varint,4,opt,name=remote_agent,json=remoteAgent,proto3" json:"remote_agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectoryWatch) Reset()         { *m = DirectoryWatch{} }
func (m *DirectoryWatch) String() string { return proto.CompactTextString(m) }
func (*DirectoryWatch) ProtoMessage()    {}
func (*DirectoryWatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{13}
}

func (m *DirectoryWatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectoryWatch.Unmarshal(m, b)
}
func (m *DirectoryWatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectoryWatch.Marshal(b, m, deterministic)
}
func (m *DirectoryWatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectoryWatch.Merge(m, src)
}
func (m *DirectoryWatch) XXX_Size() int {
	return xxx_messageInfo_DirectoryWatch.Size(m)
}
func (m *DirectoryWatch) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectoryWatch.DiscardUnknown(m)
}

var xxx_messageInfo_DirectoryWatch proto.InternalMessageInfo

func (m *DirectoryWatch) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

func (m *DirectoryWatch) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *DirectoryWatch) GetFileType() FileType {
	if m != nil {
		return m.FileType
	}
	return FileType_FILE
}

func (m *DirectoryWatch) GetRemoteAgent() bool {
	if m != nil {
		return m.RemoteAgent
	}
	return false
}

type FileTail struct {
	Filename             string     `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileFormat           FileFormat `protobuf:"varint,2,opt,name=file_format,json=fileFormat,proto3,enum=v1.model.FileFormat" json:"file_format,omitempty"`
	TimeKey              string     `protobuf:"bytes,3,opt,name=time_key,json=timeKey,proto3" json:"time_key,omitempty"`
	TimeFormat           string     `protobuf:"bytes,4,opt,name=time_format,json=timeFormat,proto3" json:"time_format,omitempty"`
	Regex                string     `protobuf:"bytes,5,opt,name=regex,proto3" json:"regex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FileTail) Reset()         { *m = FileTail{} }
func (m *FileTail) String() string { return proto.CompactTextString(m) }
func (*FileTail) ProtoMessage()    {}
func (*FileTail) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcaf5aabccbbd6a9, []int{14}
}

func (m *FileTail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileTail.Unmarshal(m, b)
}
func (m *FileTail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileTail.Marshal(b, m, deterministic)
}
func (m *FileTail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileTail.Merge(m, src)
}
func (m *FileTail) XXX_Size() int {
	return xxx_messageInfo_FileTail.Size(m)
}
func (m *FileTail) XXX_DiscardUnknown() {
	xxx_messageInfo_FileTail.DiscardUnknown(m)
}

var xxx_messageInfo_FileTail proto.InternalMessageInfo

func (m *FileTail) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileTail) GetFileFormat() FileFormat {
	if m != nil {
		return m.FileFormat
	}
	return FileFormat_PLAIN_TEXT
}

func (m *FileTail) GetTimeKey() string {
	if m != nil {
		return m.TimeKey
	}
	return ""
}

func (m *FileTail) GetTimeFormat() string {
	if m != nil {
		return m.TimeFormat
	}
	return ""
}

func (m *FileTail) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

func init() {
	proto.RegisterEnum("v1.model.TeleopRosStreamConfigurationMode", TeleopRosStreamConfigurationMode_name, TeleopRosStreamConfigurationMode_value)
	proto.RegisterEnum("v1.model.FileFormat", FileFormat_name, FileFormat_value)
	proto.RegisterEnum("v1.model.FileType", FileType_name, FileType_value)
	proto.RegisterType((*AgentConfigurationStore)(nil), "v1.model.AgentConfigurationStore")
	proto.RegisterType((*AgentConfiguration)(nil), "v1.model.AgentConfiguration")
	proto.RegisterType((*AgentConfigurationDocument)(nil), "v1.model.AgentConfigurationDocument")
	proto.RegisterMapType((map[string]string)(nil), "v1.model.AgentConfigurationDocument.TagsEntry")
	proto.RegisterType((*TeleopConfiguration)(nil), "v1.model.TeleopConfiguration")
	proto.RegisterType((*PortForwardingConfiguration)(nil), "v1.model.PortForwardingConfiguration")
	proto.RegisterType((*TeleopRosStreamConfiguration)(nil), "v1.model.TeleopRosStreamConfiguration")
	proto.RegisterType((*TelemetryConfiguration)(nil), "v1.model.TelemetryConfiguration")
	proto.RegisterType((*ApplicationConfiguration)(nil), "v1.model.ApplicationConfiguration")
	proto.RegisterMapType((map[string]string)(nil), "v1.model.ApplicationConfiguration.ConfigurationMapEntry")
	proto.RegisterType((*ResourcesConfiguration)(nil), "v1.model.ResourcesConfiguration")
	proto.RegisterType((*DiskConfiguration)(nil), "v1.model.DiskConfiguration")
	proto.RegisterType((*ROSConfiguration)(nil), "v1.model.ROSConfiguration")
	proto.RegisterType((*StreamConfiguration)(nil), "v1.model.StreamConfiguration")
	proto.RegisterMapType((map[string]string)(nil), "v1.model.StreamConfiguration.TagsEntry")
	proto.RegisterType((*Custom)(nil), "v1.model.Custom")
	proto.RegisterType((*DirectoryWatch)(nil), "v1.model.DirectoryWatch")
	proto.RegisterType((*FileTail)(nil), "v1.model.FileTail")
}

func init() { proto.RegisterFile("protos/model/v1/config.proto", fileDescriptor_fcaf5aabccbbd6a9) }

var fileDescriptor_fcaf5aabccbbd6a9 = []byte{
	// 1291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdf, 0x72, 0xdb, 0xc4,
	0x17, 0xb6, 0x12, 0x27, 0xb1, 0x8e, 0x5b, 0x47, 0xdd, 0xa6, 0xfd, 0xa9, 0x6e, 0xfa, 0x23, 0x08,
	0x28, 0x25, 0x30, 0xf6, 0x24, 0x50, 0xd2, 0xa1, 0xd0, 0x21, 0x8e, 0x9d, 0xc6, 0x6d, 0x12, 0x77,
	0x64, 0x13, 0x18, 0x2e, 0xd0, 0x28, 0xd2, 0x5a, 0xd1, 0x54, 0xd2, 0x6a, 0x56, 0xeb, 0xa4, 0xf6,
	0x0d, 0x0c, 0xef, 0xc0, 0x3d, 0x6f, 0xc0, 0x0d, 0xcf, 0xc0, 0x0d, 0x2f, 0xc5, 0xec, 0xea, 0x8f,
	0x25, 0xc7, 0x4d, 0x0a, 0x77, 0xda, 0x73, 0xbe, 0x6f, 0xf7, 0xec, 0xd9, 0xef, 0x9c, 0x63, 0xc3,
	0x7a, 0x48, 0x09, 0x23, 0x51, 0xd3, 0x27, 0x36, 0xf6, 0x9a, 0xe7, 0x5b, 0x4d, 0x8b, 0x04, 0x43,
	0xd7, 0x69, 0x08, 0x33, 0xaa, 0x9c, 0x6f, 0x35, 0x84, 0xa7, 0x7e, 0x6f, 0x16, 0x47, 0x49, 0x14,
	0x83, 0xea, 0xff, 0x77, 0x08, 0x71, 0x3c, 0xdc, 0x14, 0xab, 0xd3, 0xd1, 0xb0, 0x79, 0x41, 0xcd,
	0x30, 0xc4, 0x34, 0xf1, 0x6b, 0xbf, 0x4a, 0xf0, 0xbf, 0x5d, 0x07, 0x07, 0x6c, 0x4f, 0x6c, 0x3d,
	0xa2, 0x26, 0x73, 0x49, 0xd0, 0x67, 0x84, 0x62, 0xf4, 0x01, 0xdc, 0x34, 0xb9, 0xcb, 0x38, 0xc7,
	0x34, 0x72, 0x49, 0xa0, 0x4a, 0x1b, 0xd2, 0x23, 0x59, 0xbf, 0x21, 0x8c, 0x27, 0xb1, 0x0d, 0xb5,
	0xe0, 0xa6, 0x95, 0xa7, 0xaa, 0x0b, 0x1b, 0xd2, 0xa3, 0xea, 0xf6, 0x7a, 0x23, 0x8d, 0xae, 0x71,
	0x79, 0x7b, 0xbd, 0x48, 0xd1, 0x26, 0x80, 0x2e, 0x83, 0x50, 0x0d, 0x16, 0x5c, 0x3b, 0x39, 0x73,
	0xc1, 0xb5, 0x11, 0x82, 0x72, 0x60, 0xfa, 0x58, 0x1c, 0x20, 0xeb, 0xe2, 0x1b, 0x7d, 0x0b, 0x15,
	0x9b, 0x58, 0x23, 0x1f, 0x07, 0x4c, 0x5d, 0x14, 0x07, 0x7f, 0x78, 0xd5, 0xc1, 0xed, 0x04, 0xab,
	0x67, 0x2c, 0xed, 0x97, 0x32, 0xd4, 0xdf, 0x0e, 0x44, 0x2a, 0xac, 0xe4, 0x6f, 0xbf, 0xa8, 0xa7,
	0x4b, 0xd4, 0x82, 0x32, 0x33, 0x9d, 0x48, 0x5d, 0xd8, 0x58, 0x7c, 0x54, 0xdd, 0x6e, 0xbc, 0xcb,
	0xb1, 0x8d, 0x81, 0xe9, 0x44, 0x9d, 0x80, 0xd1, 0xb1, 0x2e, 0xb8, 0xe8, 0x19, 0xc8, 0x0c, 0x7b,
	0xd8, 0xc7, 0x8c, 0x8e, 0x93, 0xf8, 0x37, 0xa6, 0x1b, 0x0d, 0x52, 0x57, 0x31, 0x79, 0x53, 0x0a,
	0xe7, 0x53, 0x1c, 0x91, 0x11, 0xb5, 0x70, 0xa4, 0x96, 0x67, 0xf9, 0x7a, 0xea, 0x9a, 0xe1, 0x67,
	0x14, 0xd4, 0x86, 0xaa, 0x19, 0x86, 0x9e, 0x6b, 0xc5, 0x4f, 0xb7, 0x24, 0x76, 0xd0, 0x72, 0x57,
	0x99, 0x3a, 0x8b, 0x7b, 0xe4, 0x69, 0xe8, 0x31, 0x2c, 0xf3, 0x90, 0x48, 0xa8, 0x2e, 0x8b, 0x0d,
	0x1e, 0x14, 0xaf, 0x40, 0xc2, 0x22, 0x37, 0x01, 0xa3, 0x63, 0x58, 0x0d, 0x09, 0x65, 0xc6, 0x90,
	0xd0, 0x0b, 0x93, 0xda, 0x6e, 0xe0, 0xa8, 0x2b, 0x82, 0xff, 0xd1, 0x94, 0xff, 0x8a, 0x50, 0xb6,
	0x9f, 0xf9, 0x8b, 0xfb, 0xd4, 0xc2, 0x82, 0xb3, 0xbe, 0x03, 0x72, 0x96, 0x5f, 0xa4, 0xc0, 0xe2,
	0x6b, 0x3c, 0x4e, 0xd4, 0xc3, 0x3f, 0xd1, 0x1a, 0x2c, 0x9d, 0x9b, 0xde, 0x28, 0xd5, 0x4f, 0xbc,
	0xf8, 0x6a, 0xe1, 0x89, 0xa4, 0xfd, 0x04, 0xb7, 0xe7, 0xc4, 0x89, 0x9e, 0x43, 0x95, 0x92, 0xc8,
	0x88, 0x18, 0xc5, 0xa6, 0x1f, 0xa9, 0x92, 0x78, 0xe7, 0x87, 0xb3, 0x77, 0xd3, 0x49, 0xd4, 0x17,
	0x88, 0x62, 0x70, 0x40, 0x53, 0x7b, 0xa4, 0xf5, 0xe1, 0xfe, 0x15, 0xf7, 0x40, 0x5f, 0xc0, 0x0a,
	0x0e, 0xcc, 0x53, 0x0f, 0xc7, 0x62, 0xaf, 0x6e, 0xd7, 0x1b, 0x71, 0xd1, 0x36, 0xd2, 0xa2, 0x6d,
	0xb4, 0x08, 0xf1, 0x4e, 0x78, 0xbc, 0x7a, 0x0a, 0xd5, 0xfe, 0x94, 0x60, 0xfd, 0xaa, 0x08, 0xd0,
	0x03, 0x00, 0x46, 0x42, 0xd7, 0x32, 0x44, 0xd1, 0xc4, 0x89, 0x90, 0x85, 0xe5, 0x98, 0x57, 0xce,
	0xe3, 0xd4, 0xcd, 0xc6, 0x61, 0x9c, 0x93, 0xda, 0xf6, 0xdd, 0x9c, 0x76, 0x7a, 0xfd, 0x01, 0x77,
	0x0f, 0xc6, 0x21, 0x4e, 0x68, 0xfc, 0x13, 0x3d, 0x83, 0x32, 0x07, 0x08, 0xb1, 0xd6, 0xb6, 0x37,
	0xdf, 0x2d, 0x1b, 0x47, 0xc4, 0xc6, 0xba, 0xe0, 0x69, 0x3f, 0xc3, 0xdd, 0xf9, 0xb2, 0x46, 0x3b,
	0xb0, 0x52, 0x4c, 0x75, 0x4e, 0x46, 0xf3, 0x32, 0x9c, 0xa2, 0xd1, 0x67, 0xb0, 0x48, 0x49, 0x94,
	0xf4, 0x9d, 0x7a, 0xe1, 0x0a, 0x45, 0x06, 0x87, 0x69, 0x7f, 0x49, 0xa0, 0xbe, 0x4d, 0xd6, 0x08,
	0xc3, 0xad, 0x42, 0x67, 0x32, 0x7c, 0x33, 0x4c, 0xa2, 0x79, 0x72, 0x7d, 0x55, 0x34, 0x8a, 0x97,
	0x36, 0xc3, 0xb8, 0xd4, 0x15, 0x6b, 0xc6, 0x5c, 0xdf, 0x83, 0x3b, 0x73, 0xa1, 0xff, 0x4a, 0xb5,
	0xbf, 0x49, 0x70, 0x77, 0x7e, 0x85, 0xa3, 0x26, 0x94, 0x6d, 0x37, 0x7a, 0x9d, 0xc8, 0xe9, 0xfe,
	0x34, 0xf2, 0xb6, 0x1b, 0xbd, 0x2e, 0xe6, 0x44, 0x00, 0xd1, 0x0b, 0x40, 0x71, 0x36, 0x0d, 0x76,
	0x46, 0x09, 0x63, 0x1e, 0x36, 0xce, 0x26, 0x59, 0x27, 0x9f, 0x55, 0x63, 0x9b, 0x8c, 0x4e, 0x3d,
	0x1c, 0xeb, 0x51, 0x89, 0x79, 0x83, 0x84, 0x76, 0x30, 0xd1, 0x1c, 0xb8, 0x75, 0xe9, 0x18, 0xf4,
	0x1e, 0x54, 0x4f, 0x47, 0xc3, 0x21, 0xa6, 0x46, 0xe4, 0x4e, 0x70, 0xd2, 0x4a, 0x21, 0x36, 0xf5,
	0xdd, 0x09, 0x46, 0x5b, 0x70, 0x87, 0x04, 0x86, 0x8d, 0x7d, 0x33, 0xb0, 0x8d, 0x3c, 0x74, 0x41,
	0x40, 0x11, 0x09, 0xda, 0xc2, 0xd7, 0xca, 0x28, 0xda, 0x4b, 0x50, 0x66, 0x9f, 0x18, 0xed, 0x80,
	0x7a, 0x41, 0xa8, 0x67, 0x1b, 0x14, 0x0f, 0x31, 0xc5, 0x81, 0x85, 0x8d, 0x21, 0x35, 0x7d, 0x6c,
	0x64, 0x93, 0xe4, 0x8e, 0xf0, 0xeb, 0xa9, 0x7b, 0x9f, 0x7b, 0xbb, 0xb6, 0xf6, 0xf7, 0x12, 0xdc,
	0x9e, 0x57, 0x45, 0xe9, 0xd0, 0x91, 0x72, 0x43, 0xe7, 0x69, 0xa1, 0xf3, 0x7f, 0x7c, 0xa5, 0x4c,
	0x2f, 0xb5, 0xfc, 0x2d, 0x90, 0x79, 0x57, 0x11, 0x15, 0x95, 0xb4, 0x7c, 0x74, 0xb9, 0xec, 0x0e,
	0x4a, 0x7a, 0x85, 0x92, 0x48, 0x7c, 0xa3, 0x7d, 0x50, 0x38, 0xc5, 0x23, 0x96, 0xe9, 0xb9, 0x93,
	0xb8, 0x55, 0xc7, 0xcd, 0xfe, 0x5e, 0x81, 0x79, 0x98, 0x03, 0x1c, 0x94, 0xf4, 0x55, 0x4a, 0xa2,
	0xbc, 0x09, 0xed, 0xc1, 0xaa, 0xed, 0x52, 0x6c, 0x31, 0x42, 0xc7, 0xc6, 0x85, 0xc9, 0xac, 0xb3,
	0xa4, 0xe3, 0xab, 0x79, 0x85, 0x24, 0x80, 0xef, 0xb9, 0xff, 0xa0, 0xa4, 0xd7, 0xec, 0x82, 0x85,
	0xc7, 0x3f, 0x74, 0x3d, 0x6c, 0x30, 0xd3, 0xf5, 0x92, 0x7e, 0x9f, 0x8b, 0x7f, 0xdf, 0xf5, 0xf0,
	0xc0, 0x74, 0x3d, 0x1e, 0xff, 0x30, 0xf9, 0xe6, 0xea, 0x12, 0x57, 0xa6, 0x66, 0x10, 0x0d, 0x09,
	0xf5, 0x0d, 0x46, 0x31, 0x4e, 0x7a, 0x7d, 0xb1, 0x5e, 0x07, 0x29, 0x64, 0x40, 0x31, 0x3e, 0x28,
	0xe9, 0xfc, 0xde, 0x05, 0x1b, 0xda, 0x84, 0x65, 0x6b, 0x14, 0x31, 0xe2, 0xab, 0xb2, 0xe0, 0x2b,
	0x53, 0xfe, 0x9e, 0xb0, 0x1f, 0x94, 0xf4, 0x04, 0x81, 0xbe, 0x81, 0x6a, 0x5e, 0xce, 0x95, 0x77,
	0x90, 0x33, 0xb0, 0x4c, 0xc8, 0xe8, 0x4b, 0xa8, 0xd8, 0x6e, 0x14, 0x37, 0xe6, 0xdb, 0xd7, 0x36,
	0xe6, 0x0c, 0x8b, 0x76, 0x40, 0xce, 0xa4, 0xac, 0xae, 0x5d, 0x4f, 0x4c, 0xa5, 0xfd, 0x9f, 0x07,
	0x58, 0x6b, 0x75, 0xe6, 0x37, 0x98, 0x56, 0x81, 0xe5, 0x38, 0x1b, 0xda, 0xef, 0x12, 0xd4, 0x8a,
	0x6f, 0x8a, 0xd6, 0x41, 0xce, 0xde, 0x34, 0x9d, 0x0b, 0x99, 0x81, 0x7b, 0xf1, 0x1b, 0x86, 0x83,
	0x28, 0xfd, 0x2d, 0x27, 0xeb, 0x53, 0x03, 0x6a, 0xa6, 0xaf, 0xcf, 0x87, 0x46, 0x3c, 0x03, 0x66,
	0x5f, 0x9f, 0x0f, 0x8c, 0xf8, 0xed, 0xf9, 0xbc, 0x78, 0x1f, 0x6e, 0x50, 0xec, 0x13, 0x86, 0x0d,
	0xf1, 0xab, 0x51, 0xe8, 0xb6, 0xa2, 0x57, 0x63, 0x9b, 0xf8, 0xa5, 0xa4, 0xfd, 0x21, 0x41, 0x25,
	0xd5, 0x0d, 0xaa, 0x83, 0xe0, 0xe6, 0x6a, 0x2e, 0x5b, 0xa3, 0xc7, 0x50, 0x15, 0x87, 0x73, 0x31,
	0x98, 0x2c, 0x99, 0x59, 0x6b, 0xc5, 0xe3, 0xf7, 0x85, 0x4f, 0x87, 0x61, 0xf6, 0x8d, 0xee, 0x41,
	0x85, 0xb9, 0x3e, 0x36, 0x78, 0x3a, 0x17, 0xc5, 0x96, 0x2b, 0x7c, 0xfd, 0x12, 0x8f, 0x79, 0x5b,
	0x12, 0xae, 0x64, 0xc7, 0xb2, 0xf0, 0x02, 0x37, 0x25, 0xdc, 0x35, 0x58, 0xa2, 0xd8, 0xc1, 0x6f,
	0x44, 0xa1, 0xc8, 0x7a, 0xbc, 0xd8, 0xfc, 0x1a, 0x36, 0xae, 0x1b, 0x77, 0xa8, 0x0a, 0x2b, 0x7b,
	0xbd, 0xa3, 0xa3, 0xdd, 0xe3, 0xb6, 0x52, 0xe2, 0x8b, 0x5e, 0xab, 0xdf, 0xd1, 0x4f, 0x3a, 0x8a,
	0xb4, 0xf9, 0x10, 0x60, 0x1a, 0x29, 0xaa, 0x01, 0xbc, 0x3a, 0xdc, 0xed, 0x1e, 0x1b, 0x83, 0xce,
	0x0f, 0x03, 0xa5, 0x84, 0x2a, 0x50, 0x7e, 0xd1, 0xef, 0x1d, 0x2b, 0xd2, 0xe6, 0xd3, 0x24, 0x2d,
	0x3c, 0x8d, 0x15, 0x28, 0xef, 0x77, 0x0f, 0x3b, 0x4a, 0x09, 0xc9, 0xb0, 0xd4, 0x3d, 0xda, 0x7d,
	0xde, 0x51, 0x24, 0xb4, 0x0a, 0xd5, 0x57, 0xbd, 0xee, 0xf1, 0xc0, 0xd8, 0x3b, 0xec, 0x7d, 0xd7,
	0x56, 0xca, 0xdc, 0x77, 0xd2, 0x6d, 0x77, 0x7a, 0xca, 0x52, 0xeb, 0xd3, 0x1f, 0x3f, 0x71, 0x5c,
	0x76, 0x36, 0x3a, 0x6d, 0x58, 0xc4, 0x6f, 0x8a, 0xb3, 0x02, 0xd6, 0xed, 0x35, 0x1d, 0x1c, 0x08,
	0x0d, 0x36, 0x1d, 0xc2, 0xff, 0x28, 0x88, 0xc4, 0x9d, 0x2e, 0x0b, 0xd3, 0xe7, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x33, 0xa0, 0x91, 0x3c, 0x70, 0x0c, 0x00, 0x00,
}
