// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/model/v1/datapoint.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Datapoint struct {
	Stream    string            `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Timestamp int64             `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tags      map[string]string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Types that are valid to be assigned to Data:
	//	*Datapoint_Text
	//	*Datapoint_Numeric
	//	*Datapoint_NumericSet
	//	*Datapoint_Bitset
	//	*Datapoint_File
	//	*Datapoint_Image
	//	*Datapoint_PointCloud
	//	*Datapoint_Location
	//	*Datapoint_Localization
	//	*Datapoint_Health
	//	*Datapoint_Json
	//	*Datapoint_Battery
	//	*Datapoint_Video
	Data                 isDatapoint_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Datapoint) Reset()         { *m = Datapoint{} }
func (m *Datapoint) String() string { return proto.CompactTextString(m) }
func (*Datapoint) ProtoMessage()    {}
func (*Datapoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4daa958809a1527, []int{0}
}

func (m *Datapoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Datapoint.Unmarshal(m, b)
}
func (m *Datapoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Datapoint.Marshal(b, m, deterministic)
}
func (m *Datapoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Datapoint.Merge(m, src)
}
func (m *Datapoint) XXX_Size() int {
	return xxx_messageInfo_Datapoint.Size(m)
}
func (m *Datapoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Datapoint.DiscardUnknown(m)
}

var xxx_messageInfo_Datapoint proto.InternalMessageInfo

func (m *Datapoint) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *Datapoint) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Datapoint) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type isDatapoint_Data interface {
	isDatapoint_Data()
}

type Datapoint_Text struct {
	Text *Text `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type Datapoint_Numeric struct {
	Numeric *Numeric `protobuf:"bytes,5,opt,name=numeric,proto3,oneof"`
}

type Datapoint_NumericSet struct {
	NumericSet *NumericSet `protobuf:"bytes,17,opt,name=numeric_set,json=numericSet,proto3,oneof"`
}

type Datapoint_Bitset struct {
	Bitset *Bitset `protobuf:"bytes,7,opt,name=bitset,proto3,oneof"`
}

type Datapoint_File struct {
	File *File `protobuf:"bytes,8,opt,name=file,proto3,oneof"`
}

type Datapoint_Image struct {
	Image *Image `protobuf:"bytes,9,opt,name=image,proto3,oneof"`
}

type Datapoint_PointCloud struct {
	PointCloud *PointCloud `protobuf:"bytes,10,opt,name=point_cloud,json=pointCloud,proto3,oneof"`
}

type Datapoint_Location struct {
	Location *Location `protobuf:"bytes,11,opt,name=location,proto3,oneof"`
}

type Datapoint_Localization struct {
	Localization *Localization `protobuf:"bytes,12,opt,name=localization,proto3,oneof"`
}

type Datapoint_Health struct {
	Health *Health `protobuf:"bytes,13,opt,name=health,proto3,oneof"`
}

type Datapoint_Json struct {
	Json *Json `protobuf:"bytes,14,opt,name=json,proto3,oneof"`
}

type Datapoint_Battery struct {
	Battery *Battery `protobuf:"bytes,15,opt,name=battery,proto3,oneof"`
}

type Datapoint_Video struct {
	Video *Video `protobuf:"bytes,16,opt,name=video,proto3,oneof"`
}

func (*Datapoint_Text) isDatapoint_Data() {}

func (*Datapoint_Numeric) isDatapoint_Data() {}

func (*Datapoint_NumericSet) isDatapoint_Data() {}

func (*Datapoint_Bitset) isDatapoint_Data() {}

func (*Datapoint_File) isDatapoint_Data() {}

func (*Datapoint_Image) isDatapoint_Data() {}

func (*Datapoint_PointCloud) isDatapoint_Data() {}

func (*Datapoint_Location) isDatapoint_Data() {}

func (*Datapoint_Localization) isDatapoint_Data() {}

func (*Datapoint_Health) isDatapoint_Data() {}

func (*Datapoint_Json) isDatapoint_Data() {}

func (*Datapoint_Battery) isDatapoint_Data() {}

func (*Datapoint_Video) isDatapoint_Data() {}

func (m *Datapoint) GetData() isDatapoint_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Datapoint) GetText() *Text {
	if x, ok := m.GetData().(*Datapoint_Text); ok {
		return x.Text
	}
	return nil
}

func (m *Datapoint) GetNumeric() *Numeric {
	if x, ok := m.GetData().(*Datapoint_Numeric); ok {
		return x.Numeric
	}
	return nil
}

func (m *Datapoint) GetNumericSet() *NumericSet {
	if x, ok := m.GetData().(*Datapoint_NumericSet); ok {
		return x.NumericSet
	}
	return nil
}

func (m *Datapoint) GetBitset() *Bitset {
	if x, ok := m.GetData().(*Datapoint_Bitset); ok {
		return x.Bitset
	}
	return nil
}

func (m *Datapoint) GetFile() *File {
	if x, ok := m.GetData().(*Datapoint_File); ok {
		return x.File
	}
	return nil
}

func (m *Datapoint) GetImage() *Image {
	if x, ok := m.GetData().(*Datapoint_Image); ok {
		return x.Image
	}
	return nil
}

func (m *Datapoint) GetPointCloud() *PointCloud {
	if x, ok := m.GetData().(*Datapoint_PointCloud); ok {
		return x.PointCloud
	}
	return nil
}

func (m *Datapoint) GetLocation() *Location {
	if x, ok := m.GetData().(*Datapoint_Location); ok {
		return x.Location
	}
	return nil
}

func (m *Datapoint) GetLocalization() *Localization {
	if x, ok := m.GetData().(*Datapoint_Localization); ok {
		return x.Localization
	}
	return nil
}

func (m *Datapoint) GetHealth() *Health {
	if x, ok := m.GetData().(*Datapoint_Health); ok {
		return x.Health
	}
	return nil
}

func (m *Datapoint) GetJson() *Json {
	if x, ok := m.GetData().(*Datapoint_Json); ok {
		return x.Json
	}
	return nil
}

func (m *Datapoint) GetBattery() *Battery {
	if x, ok := m.GetData().(*Datapoint_Battery); ok {
		return x.Battery
	}
	return nil
}

func (m *Datapoint) GetVideo() *Video {
	if x, ok := m.GetData().(*Datapoint_Video); ok {
		return x.Video
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Datapoint) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Datapoint_Text)(nil),
		(*Datapoint_Numeric)(nil),
		(*Datapoint_NumericSet)(nil),
		(*Datapoint_Bitset)(nil),
		(*Datapoint_File)(nil),
		(*Datapoint_Image)(nil),
		(*Datapoint_PointCloud)(nil),
		(*Datapoint_Location)(nil),
		(*Datapoint_Localization)(nil),
		(*Datapoint_Health)(nil),
		(*Datapoint_Json)(nil),
		(*Datapoint_Battery)(nil),
		(*Datapoint_Video)(nil),
	}
}

type ControlDatapoint struct {
	Stream    string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*ControlDatapoint_Bitset
	//	*ControlDatapoint_Twist
	//	*ControlDatapoint_Pose
	Data                 isControlDatapoint_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ControlDatapoint) Reset()         { *m = ControlDatapoint{} }
func (m *ControlDatapoint) String() string { return proto.CompactTextString(m) }
func (*ControlDatapoint) ProtoMessage()    {}
func (*ControlDatapoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4daa958809a1527, []int{1}
}

func (m *ControlDatapoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlDatapoint.Unmarshal(m, b)
}
func (m *ControlDatapoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlDatapoint.Marshal(b, m, deterministic)
}
func (m *ControlDatapoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlDatapoint.Merge(m, src)
}
func (m *ControlDatapoint) XXX_Size() int {
	return xxx_messageInfo_ControlDatapoint.Size(m)
}
func (m *ControlDatapoint) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlDatapoint.DiscardUnknown(m)
}

var xxx_messageInfo_ControlDatapoint proto.InternalMessageInfo

func (m *ControlDatapoint) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *ControlDatapoint) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type isControlDatapoint_Data interface {
	isControlDatapoint_Data()
}

type ControlDatapoint_Bitset struct {
	Bitset *Bitset `protobuf:"bytes,3,opt,name=bitset,proto3,oneof"`
}

type ControlDatapoint_Twist struct {
	Twist *Twist `protobuf:"bytes,4,opt,name=twist,proto3,oneof"`
}

type ControlDatapoint_Pose struct {
	Pose *Transform `protobuf:"bytes,5,opt,name=pose,proto3,oneof"`
}

func (*ControlDatapoint_Bitset) isControlDatapoint_Data() {}

func (*ControlDatapoint_Twist) isControlDatapoint_Data() {}

func (*ControlDatapoint_Pose) isControlDatapoint_Data() {}

func (m *ControlDatapoint) GetData() isControlDatapoint_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ControlDatapoint) GetBitset() *Bitset {
	if x, ok := m.GetData().(*ControlDatapoint_Bitset); ok {
		return x.Bitset
	}
	return nil
}

func (m *ControlDatapoint) GetTwist() *Twist {
	if x, ok := m.GetData().(*ControlDatapoint_Twist); ok {
		return x.Twist
	}
	return nil
}

func (m *ControlDatapoint) GetPose() *Transform {
	if x, ok := m.GetData().(*ControlDatapoint_Pose); ok {
		return x.Pose
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ControlDatapoint) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ControlDatapoint_Bitset)(nil),
		(*ControlDatapoint_Twist)(nil),
		(*ControlDatapoint_Pose)(nil),
	}
}

func init() {
	proto.RegisterType((*Datapoint)(nil), "v1.model.Datapoint")
	proto.RegisterMapType((map[string]string)(nil), "v1.model.Datapoint.TagsEntry")
	proto.RegisterType((*ControlDatapoint)(nil), "v1.model.ControlDatapoint")
}

func init() { proto.RegisterFile("protos/model/v1/datapoint.proto", fileDescriptor_d4daa958809a1527) }

var fileDescriptor_d4daa958809a1527 = []byte{
	// 597 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x5f, 0x6f, 0xd3, 0x3c,
	0x14, 0xc6, 0x93, 0x35, 0x4d, 0x1b, 0x77, 0xef, 0xd6, 0xf9, 0x9d, 0x26, 0xab, 0x0c, 0x51, 0x4d,
	0x48, 0xeb, 0x40, 0x24, 0x74, 0x5c, 0x0c, 0x21, 0xae, 0x3a, 0x98, 0xb2, 0x09, 0x01, 0x0a, 0x15,
	0x17, 0xdc, 0x4c, 0x6e, 0xeb, 0xa5, 0x86, 0x24, 0xae, 0x62, 0xb7, 0xac, 0x7c, 0x11, 0xbe, 0x16,
	0x1f, 0x09, 0x1d, 0xe7, 0xdf, 0x96, 0x0a, 0x71, 0xc1, 0x5d, 0x7c, 0x7e, 0xcf, 0xe3, 0x1e, 0x3f,
	0x3e, 0x2e, 0x7a, 0xb4, 0x48, 0x85, 0x12, 0xd2, 0x8b, 0xc5, 0x8c, 0x45, 0xde, 0x6a, 0xe8, 0xcd,
	0xa8, 0xa2, 0x0b, 0xc1, 0x13, 0xe5, 0x6a, 0x82, 0xdb, 0xab, 0xa1, 0xab, 0x61, 0xaf, 0x57, 0x97,
	0xde, 0xf0, 0x88, 0x65, 0xaa, 0xde, 0x61, 0x9d, 0xcd, 0x19, 0x8d, 0xd4, 0x3c, 0xa7, 0x1b, 0xce,
	0x98, 0x96, 0xac, 0x5f, 0x67, 0x09, 0x5d, 0xf1, 0x90, 0x2a, 0x2e, 0x92, 0x3f, 0xb9, 0x15, 0xbb,
	0xcd, 0xbb, 0xeb, 0x3d, 0xd8, 0xd8, 0x99, 0xcd, 0x38, 0xcd, 0xe0, 0xd1, 0x4f, 0x1b, 0x39, 0x6f,
	0x8a, 0xe3, 0xe0, 0x03, 0x64, 0x4b, 0x95, 0x32, 0x1a, 0x13, 0xb3, 0x6f, 0x0e, 0x9c, 0x20, 0x5f,
	0xe1, 0x43, 0xe4, 0x28, 0x1e, 0x33, 0xa9, 0x68, 0xbc, 0x20, 0x5b, 0x7d, 0x73, 0xd0, 0x08, 0xaa,
	0x02, 0x1e, 0x22, 0x4b, 0xd1, 0x50, 0x92, 0x46, 0xbf, 0x31, 0xe8, 0x9c, 0x3e, 0x74, 0x8b, 0x34,
	0xdc, 0x72, 0x63, 0x77, 0x4c, 0x43, 0xf9, 0x36, 0x51, 0xe9, 0x3a, 0xd0, 0x52, 0xfc, 0x18, 0x59,
	0xd0, 0x21, 0xb1, 0xfa, 0xe6, 0xa0, 0x73, 0xba, 0x53, 0x59, 0xc6, 0xec, 0x56, 0xf9, 0x46, 0xa0,
	0x29, 0x7e, 0x86, 0x5a, 0xc9, 0x32, 0x66, 0x29, 0x9f, 0x92, 0xa6, 0x16, 0xee, 0x55, 0xc2, 0xf7,
	0x19, 0xf0, 0x8d, 0xa0, 0xd0, 0xe0, 0x33, 0xd4, 0xc9, 0x3f, 0xaf, 0x25, 0x53, 0x64, 0x4f, 0x5b,
	0xf6, 0x37, 0x2c, 0x9f, 0x18, 0xfc, 0x02, 0x4a, 0xca, 0x15, 0x7e, 0x82, 0xec, 0x09, 0x57, 0xe0,
	0x69, 0x69, 0x4f, 0xb7, 0xf2, 0x8c, 0x74, 0xdd, 0x37, 0x82, 0x5c, 0x01, 0x9d, 0xc3, 0x9d, 0x92,
	0x76, 0xbd, 0xf3, 0x0b, 0x1e, 0x31, 0xe8, 0x1c, 0x28, 0x3e, 0x46, 0x4d, 0x1e, 0xd3, 0x90, 0x11,
	0x47, 0xcb, 0x76, 0x2b, 0xd9, 0x25, 0x94, 0x7d, 0x23, 0xc8, 0x38, 0xf4, 0xac, 0x13, 0xba, 0x9e,
	0x46, 0x62, 0x39, 0x23, 0xa8, 0xde, 0xf3, 0x47, 0x80, 0xe7, 0xc0, 0xa0, 0xe7, 0x45, 0xb9, 0xc2,
	0xcf, 0x51, 0x3b, 0x12, 0x53, 0x3d, 0x03, 0xa4, 0xa3, 0x5d, 0xb8, 0x72, 0xbd, 0xcb, 0x89, 0x6f,
	0x04, 0xa5, 0x0a, 0xbf, 0x46, 0xdb, 0xf0, 0x1d, 0xf1, 0x1f, 0x99, 0x6b, 0x5b, 0xbb, 0x0e, 0xee,
	0xbb, 0x0a, 0xea, 0x1b, 0xc1, 0x3d, 0x35, 0x64, 0x94, 0xcd, 0x2b, 0xf9, 0xaf, 0x9e, 0x91, 0xaf,
	0xeb, 0x90, 0x51, 0xa6, 0x80, 0x8c, 0xbe, 0x4a, 0x91, 0x90, 0x9d, 0x7a, 0x46, 0x57, 0x52, 0xef,
	0xac, 0x29, 0xdc, 0xee, 0x84, 0x2a, 0xc5, 0xd2, 0x35, 0xd9, 0xad, 0xdf, 0xee, 0x28, 0x03, 0x70,
	0xbb, 0xb9, 0x06, 0x22, 0x5d, 0xf1, 0x19, 0x13, 0xa4, 0x5b, 0x8f, 0xf4, 0x33, 0x94, 0x21, 0x52,
	0xcd, 0x7b, 0x67, 0xc8, 0x29, 0xc7, 0x0d, 0x77, 0x51, 0xe3, 0x1b, 0x5b, 0xe7, 0xe3, 0x0c, 0x9f,
	0x78, 0x1f, 0x35, 0x57, 0x34, 0x5a, 0x32, 0x3d, 0xc7, 0x4e, 0x90, 0x2d, 0x5e, 0x6d, 0xbd, 0x34,
	0x47, 0x36, 0xb2, 0xe0, 0x65, 0x5f, 0x59, 0x6d, 0xbb, 0xdb, 0x3a, 0xfa, 0x65, 0xa2, 0xee, 0xb9,
	0x48, 0x54, 0x2a, 0xa2, 0x7f, 0x7d, 0x20, 0xd5, 0x7c, 0x35, 0xfe, 0x3a, 0x5f, 0xc7, 0xa8, 0xa9,
	0xbe, 0x73, 0x59, 0x3c, 0x8d, 0x3b, 0xc7, 0x1c, 0x43, 0x19, 0x8e, 0xa9, 0x39, 0x3e, 0x41, 0xd6,
	0x42, 0x48, 0x96, 0xbf, 0x8c, 0xff, 0xef, 0xe8, 0x52, 0x9a, 0xc8, 0x1b, 0x91, 0xc6, 0x90, 0x34,
	0x48, 0x8a, 0x83, 0x8d, 0x9e, 0x7e, 0x39, 0x09, 0xb9, 0x9a, 0x2f, 0x27, 0xee, 0x54, 0xc4, 0xde,
	0x85, 0x48, 0x63, 0x9a, 0xa8, 0xcb, 0x0f, 0x5e, 0xc8, 0x12, 0xfd, 0x6f, 0xe0, 0x85, 0x42, 0xff,
	0x3f, 0xc0, 0x36, 0x13, 0x5b, 0x97, 0x5e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x5c, 0xf9,
	0x46, 0xfe, 0x04, 0x00, 0x00,
}
