// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.7
// source: protos/model/v1/event.proto

package model

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Severity int32

const (
	Severity_INFO     Severity = 0
	Severity_WARNING  Severity = 1
	Severity_ERROR    Severity = 2
	Severity_CRITICAL Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "INFO",
		1: "WARNING",
		2: "ERROR",
		3: "CRITICAL",
	}
	Severity_value = map[string]int32{
		"INFO":     0,
		"WARNING":  1,
		"ERROR":    2,
		"CRITICAL": 3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_model_v1_event_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_protos_model_v1_event_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_protos_model_v1_event_proto_rawDescGZIP(), []int{0}
}

type ThresholdOperator int32

const (
	ThresholdOperator_LT  ThresholdOperator = 0
	ThresholdOperator_LTE ThresholdOperator = 1
	ThresholdOperator_GT  ThresholdOperator = 2
	ThresholdOperator_GTE ThresholdOperator = 3
	ThresholdOperator_EQ  ThresholdOperator = 4
	ThresholdOperator_NEQ ThresholdOperator = 5
)

// Enum value maps for ThresholdOperator.
var (
	ThresholdOperator_name = map[int32]string{
		0: "LT",
		1: "LTE",
		2: "GT",
		3: "GTE",
		4: "EQ",
		5: "NEQ",
	}
	ThresholdOperator_value = map[string]int32{
		"LT":  0,
		"LTE": 1,
		"GT":  2,
		"GTE": 3,
		"EQ":  4,
		"NEQ": 5,
	}
)

func (x ThresholdOperator) Enum() *ThresholdOperator {
	p := new(ThresholdOperator)
	*p = x
	return p
}

func (x ThresholdOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThresholdOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_model_v1_event_proto_enumTypes[1].Descriptor()
}

func (ThresholdOperator) Type() protoreflect.EnumType {
	return &file_protos_model_v1_event_proto_enumTypes[1]
}

func (x ThresholdOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThresholdOperator.Descriptor instead.
func (ThresholdOperator) EnumDescriptor() ([]byte, []int) {
	return file_protos_model_v1_event_proto_rawDescGZIP(), []int{1}
}

type BitsetOperator int32

const (
	BitsetOperator_ANY BitsetOperator = 0
	BitsetOperator_ALL BitsetOperator = 1
)

// Enum value maps for BitsetOperator.
var (
	BitsetOperator_name = map[int32]string{
		0: "ANY",
		1: "ALL",
	}
	BitsetOperator_value = map[string]int32{
		"ANY": 0,
		"ALL": 1,
	}
)

func (x BitsetOperator) Enum() *BitsetOperator {
	p := new(BitsetOperator)
	*p = x
	return p
}

func (x BitsetOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BitsetOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_model_v1_event_proto_enumTypes[2].Descriptor()
}

func (BitsetOperator) Type() protoreflect.EnumType {
	return &file_protos_model_v1_event_proto_enumTypes[2]
}

func (x BitsetOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BitsetOperator.Descriptor instead.
func (BitsetOperator) EnumDescriptor() ([]byte, []int) {
	return file_protos_model_v1_event_proto_rawDescGZIP(), []int{2}
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp           int64             `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EndTimestamp        int64             `protobuf:"varint,8,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	Message             string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StreamName          string            `protobuf:"bytes,3,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	StreamType          string            `protobuf:"bytes,4,opt,name=stream_type,json=streamType,proto3" json:"stream_type,omitempty"`
	NotificationEnabled bool              `protobuf:"varint,5,opt,name=notification_enabled,json=notificationEnabled,proto3" json:"notification_enabled,omitempty"`
	Severity            Severity          `protobuf:"varint,9,opt,name=severity,proto3,enum=v1.model.Severity" json:"severity,omitempty"`
	Tags                map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_model_v1_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *Event) GetStreamType() string {
	if x != nil {
		return x.StreamType
	}
	return ""
}

func (x *Event) GetNotificationEnabled() bool {
	if x != nil {
		return x.NotificationEnabled
	}
	return false
}

func (x *Event) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_INFO
}

func (x *Event) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AgentEventConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventTriggers []*AgentEventTrigger `protobuf:"bytes,1,rep,name=event_triggers,json=eventTriggers,proto3" json:"event_triggers,omitempty"`
	LastUpdated   int64                `protobuf:"varint,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
}

func (x *AgentEventConfiguration) Reset() {
	*x = AgentEventConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_model_v1_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentEventConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEventConfiguration) ProtoMessage() {}

func (x *AgentEventConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEventConfiguration.ProtoReflect.Descriptor instead.
func (*AgentEventConfiguration) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *AgentEventConfiguration) GetEventTriggers() []*AgentEventTrigger {
	if x != nil {
		return x.EventTriggers
	}
	return nil
}

func (x *AgentEventConfiguration) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

type AgentEventTrigger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stream   string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Interval int64  `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`
	// Types that are assignable to Condition:
	//	*AgentEventTrigger_Presence
	//	*AgentEventTrigger_Threshold
	//	*AgentEventTrigger_Regex
	//	*AgentEventTrigger_Bitset
	Condition isAgentEventTrigger_Condition `protobuf_oneof:"condition"`
}

func (x *AgentEventTrigger) Reset() {
	*x = AgentEventTrigger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_model_v1_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentEventTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEventTrigger) ProtoMessage() {}

func (x *AgentEventTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEventTrigger.ProtoReflect.Descriptor instead.
func (*AgentEventTrigger) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *AgentEventTrigger) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentEventTrigger) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *AgentEventTrigger) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (m *AgentEventTrigger) GetCondition() isAgentEventTrigger_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (x *AgentEventTrigger) GetPresence() *PresenceEventTriggerCondition {
	if x, ok := x.GetCondition().(*AgentEventTrigger_Presence); ok {
		return x.Presence
	}
	return nil
}

func (x *AgentEventTrigger) GetThreshold() *ThresholdEventTriggerCondition {
	if x, ok := x.GetCondition().(*AgentEventTrigger_Threshold); ok {
		return x.Threshold
	}
	return nil
}

func (x *AgentEventTrigger) GetRegex() *RegexEventTriggerCondition {
	if x, ok := x.GetCondition().(*AgentEventTrigger_Regex); ok {
		return x.Regex
	}
	return nil
}

func (x *AgentEventTrigger) GetBitset() *BitsetEventTriggerCondition {
	if x, ok := x.GetCondition().(*AgentEventTrigger_Bitset); ok {
		return x.Bitset
	}
	return nil
}

type isAgentEventTrigger_Condition interface {
	isAgentEventTrigger_Condition()
}

type AgentEventTrigger_Presence struct {
	Presence *PresenceEventTriggerCondition `protobuf:"bytes,4,opt,name=presence,proto3,oneof"`
}

type AgentEventTrigger_Threshold struct {
	Threshold *ThresholdEventTriggerCondition `protobuf:"bytes,5,opt,name=threshold,proto3,oneof"`
}

type AgentEventTrigger_Regex struct {
	Regex *RegexEventTriggerCondition `protobuf:"bytes,6,opt,name=regex,proto3,oneof"`
}

type AgentEventTrigger_Bitset struct {
	Bitset *BitsetEventTriggerCondition `protobuf:"bytes,7,opt,name=bitset,proto3,oneof"`
}

func (*AgentEventTrigger_Presence) isAgentEventTrigger_Condition() {}

func (*AgentEventTrigger_Threshold) isAgentEventTrigger_Condition() {}

func (*AgentEventTrigger_Regex) isAgentEventTrigger_Condition() {}

func (*AgentEventTrigger_Bitset) isAgentEventTrigger_Condition() {}

type PresenceEventTriggerCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PresenceEventTriggerCondition) Reset() {
	*x = PresenceEventTriggerCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_model_v1_event_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PresenceEventTriggerCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceEventTriggerCondition) ProtoMessage() {}

func (x *PresenceEventTriggerCondition) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_event_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceEventTriggerCondition.ProtoReflect.Descriptor instead.
func (*PresenceEventTriggerCondition) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_event_proto_rawDescGZIP(), []int{3}
}

type ThresholdEventTriggerCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    float64           `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Operator ThresholdOperator `protobuf:"varint,2,opt,name=operator,proto3,enum=v1.model.ThresholdOperator" json:"operator,omitempty"`
}

func (x *ThresholdEventTriggerCondition) Reset() {
	*x = ThresholdEventTriggerCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_model_v1_event_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThresholdEventTriggerCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdEventTriggerCondition) ProtoMessage() {}

func (x *ThresholdEventTriggerCondition) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_event_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdEventTriggerCondition.ProtoReflect.Descriptor instead.
func (*ThresholdEventTriggerCondition) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *ThresholdEventTriggerCondition) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ThresholdEventTriggerCondition) GetOperator() ThresholdOperator {
	if x != nil {
		return x.Operator
	}
	return ThresholdOperator_LT
}

type RegexEventTriggerCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *RegexEventTriggerCondition) Reset() {
	*x = RegexEventTriggerCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_model_v1_event_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegexEventTriggerCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegexEventTriggerCondition) ProtoMessage() {}

func (x *RegexEventTriggerCondition) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_event_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegexEventTriggerCondition.ProtoReflect.Descriptor instead.
func (*RegexEventTriggerCondition) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *RegexEventTriggerCondition) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type BitsetEventTriggerCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BitConditions []*BitsetCondition `protobuf:"bytes,1,rep,name=bit_conditions,json=bitConditions,proto3" json:"bit_conditions,omitempty"`
	Operator      BitsetOperator     `protobuf:"varint,2,opt,name=operator,proto3,enum=v1.model.BitsetOperator" json:"operator,omitempty"`
}

func (x *BitsetEventTriggerCondition) Reset() {
	*x = BitsetEventTriggerCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_model_v1_event_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BitsetEventTriggerCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitsetEventTriggerCondition) ProtoMessage() {}

func (x *BitsetEventTriggerCondition) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_event_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitsetEventTriggerCondition.ProtoReflect.Descriptor instead.
func (*BitsetEventTriggerCondition) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_event_proto_rawDescGZIP(), []int{6}
}

func (x *BitsetEventTriggerCondition) GetBitConditions() []*BitsetCondition {
	if x != nil {
		return x.BitConditions
	}
	return nil
}

func (x *BitsetEventTriggerCondition) GetOperator() BitsetOperator {
	if x != nil {
		return x.Operator
	}
	return BitsetOperator_ANY
}

type BitsetCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	True  bool   `protobuf:"varint,2,opt,name=true,proto3" json:"true,omitempty"`
	False bool   `protobuf:"varint,3,opt,name=false,proto3" json:"false,omitempty"`
}

func (x *BitsetCondition) Reset() {
	*x = BitsetCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_model_v1_event_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BitsetCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitsetCondition) ProtoMessage() {}

func (x *BitsetCondition) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_event_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitsetCondition.ProtoReflect.Descriptor instead.
func (*BitsetCondition) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_event_proto_rawDescGZIP(), []int{7}
}

func (x *BitsetCondition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BitsetCondition) GetTrue() bool {
	if x != nil {
		return x.True
	}
	return false
}

func (x *BitsetCondition) GetFalse() bool {
	if x != nil {
		return x.False
	}
	return false
}

var File_protos_model_v1_event_proto protoreflect.FileDescriptor

var file_protos_model_v1_event_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x76,
	0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x76,
	0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0xf7, 0x02, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x31, 0x0a, 0x14, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x54, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x1a, 0x37, 0x0a, 0x09, 0x54, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x4a, 0x04, 0x08, 0x07, 0x10,
	0x08, 0x22, 0x80, 0x01, 0x0a, 0x17, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a,
	0x0e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67,
	0x65, 0x72, 0x52, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x22, 0xf4, 0x02, 0x0a, 0x11, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x45,
	0x0a, 0x08, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x65,
	0x73, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f,
	0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12,
	0x3c, 0x0a, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x65, 0x78, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x12, 0x3f, 0x0a,
	0x06, 0x62, 0x69, 0x74, 0x73, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x42, 0x69, 0x74, 0x73, 0x65, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x62, 0x69, 0x74, 0x73, 0x65, 0x74, 0x42, 0x0b,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1f, 0x0a, 0x1d, 0x50,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6f, 0x0a, 0x1e,
	0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x32, 0x0a,
	0x1a, 0x52, 0x65, 0x67, 0x65, 0x78, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x95, 0x01, 0x0a, 0x1b, 0x42, 0x69, 0x74, 0x73, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x40, 0x0a, 0x0e, 0x62, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x42, 0x69, 0x74, 0x73, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x62, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x34, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x42, 0x69, 0x74, 0x73, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52,
	0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x4d, 0x0a, 0x0f, 0x42, 0x69, 0x74,
	0x73, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x72, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x74, 0x72,
	0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x2a, 0x3a, 0x0a, 0x08, 0x53, 0x65, 0x76, 0x65,
	0x72, 0x69, 0x74, 0x79, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x52, 0x49, 0x54, 0x49, 0x43,
	0x41, 0x4c, 0x10, 0x03, 0x2a, 0x46, 0x0a, 0x11, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c,
	0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x54, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x54, 0x45, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x47, 0x54,
	0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x54, 0x45, 0x10, 0x03, 0x12, 0x06, 0x0a, 0x02, 0x45,
	0x51, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x51, 0x10, 0x05, 0x2a, 0x22, 0x0a, 0x0e,
	0x42, 0x69, 0x74, 0x73, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x07,
	0x0a, 0x03, 0x41, 0x4e, 0x59, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x01,
	0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x74, 0x49, 0x4f, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_model_v1_event_proto_rawDescOnce sync.Once
	file_protos_model_v1_event_proto_rawDescData = file_protos_model_v1_event_proto_rawDesc
)

func file_protos_model_v1_event_proto_rawDescGZIP() []byte {
	file_protos_model_v1_event_proto_rawDescOnce.Do(func() {
		file_protos_model_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_model_v1_event_proto_rawDescData)
	})
	return file_protos_model_v1_event_proto_rawDescData
}

var file_protos_model_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protos_model_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_model_v1_event_proto_goTypes = []interface{}{
	(Severity)(0),                          // 0: v1.model.Severity
	(ThresholdOperator)(0),                 // 1: v1.model.ThresholdOperator
	(BitsetOperator)(0),                    // 2: v1.model.BitsetOperator
	(*Event)(nil),                          // 3: v1.model.Event
	(*AgentEventConfiguration)(nil),        // 4: v1.model.AgentEventConfiguration
	(*AgentEventTrigger)(nil),              // 5: v1.model.AgentEventTrigger
	(*PresenceEventTriggerCondition)(nil),  // 6: v1.model.PresenceEventTriggerCondition
	(*ThresholdEventTriggerCondition)(nil), // 7: v1.model.ThresholdEventTriggerCondition
	(*RegexEventTriggerCondition)(nil),     // 8: v1.model.RegexEventTriggerCondition
	(*BitsetEventTriggerCondition)(nil),    // 9: v1.model.BitsetEventTriggerCondition
	(*BitsetCondition)(nil),                // 10: v1.model.BitsetCondition
	nil,                                    // 11: v1.model.Event.TagsEntry
}
var file_protos_model_v1_event_proto_depIdxs = []int32{
	0,  // 0: v1.model.Event.severity:type_name -> v1.model.Severity
	11, // 1: v1.model.Event.tags:type_name -> v1.model.Event.TagsEntry
	5,  // 2: v1.model.AgentEventConfiguration.event_triggers:type_name -> v1.model.AgentEventTrigger
	6,  // 3: v1.model.AgentEventTrigger.presence:type_name -> v1.model.PresenceEventTriggerCondition
	7,  // 4: v1.model.AgentEventTrigger.threshold:type_name -> v1.model.ThresholdEventTriggerCondition
	8,  // 5: v1.model.AgentEventTrigger.regex:type_name -> v1.model.RegexEventTriggerCondition
	9,  // 6: v1.model.AgentEventTrigger.bitset:type_name -> v1.model.BitsetEventTriggerCondition
	1,  // 7: v1.model.ThresholdEventTriggerCondition.operator:type_name -> v1.model.ThresholdOperator
	10, // 8: v1.model.BitsetEventTriggerCondition.bit_conditions:type_name -> v1.model.BitsetCondition
	2,  // 9: v1.model.BitsetEventTriggerCondition.operator:type_name -> v1.model.BitsetOperator
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_protos_model_v1_event_proto_init() }
func file_protos_model_v1_event_proto_init() {
	if File_protos_model_v1_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_model_v1_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_model_v1_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentEventConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_model_v1_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentEventTrigger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_model_v1_event_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PresenceEventTriggerCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_model_v1_event_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThresholdEventTriggerCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_model_v1_event_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegexEventTriggerCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_model_v1_event_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BitsetEventTriggerCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_model_v1_event_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BitsetCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_model_v1_event_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*AgentEventTrigger_Presence)(nil),
		(*AgentEventTrigger_Threshold)(nil),
		(*AgentEventTrigger_Regex)(nil),
		(*AgentEventTrigger_Bitset)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_model_v1_event_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_model_v1_event_proto_goTypes,
		DependencyIndexes: file_protos_model_v1_event_proto_depIdxs,
		EnumInfos:         file_protos_model_v1_event_proto_enumTypes,
		MessageInfos:      file_protos_model_v1_event_proto_msgTypes,
	}.Build()
	File_protos_model_v1_event_proto = out.File
	file_protos_model_v1_event_proto_rawDesc = nil
	file_protos_model_v1_event_proto_goTypes = nil
	file_protos_model_v1_event_proto_depIdxs = nil
}
