// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/model/v1/health.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthStatus int32

const (
	HealthStatus_HEALTH_UNKNOWN     HealthStatus = 0
	HealthStatus_HEALTH_OPERATIONAL HealthStatus = 1
	HealthStatus_HEALTH_OFFLINE     HealthStatus = 2
	HealthStatus_HEALTH_ERROR       HealthStatus = 3
)

var HealthStatus_name = map[int32]string{
	0: "HEALTH_UNKNOWN",
	1: "HEALTH_OPERATIONAL",
	2: "HEALTH_OFFLINE",
	3: "HEALTH_ERROR",
}

var HealthStatus_value = map[string]int32{
	"HEALTH_UNKNOWN":     0,
	"HEALTH_OPERATIONAL": 1,
	"HEALTH_OFFLINE":     2,
	"HEALTH_ERROR":       3,
}

func (x HealthStatus) String() string {
	return proto.EnumName(HealthStatus_name, int32(x))
}

func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a9e68dd7d671de82, []int{0}
}

type Health struct {
	Status               HealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=v1.model.HealthStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Health) Reset()         { *m = Health{} }
func (m *Health) String() string { return proto.CompactTextString(m) }
func (*Health) ProtoMessage()    {}
func (*Health) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e68dd7d671de82, []int{0}
}

func (m *Health) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Health.Unmarshal(m, b)
}
func (m *Health) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Health.Marshal(b, m, deterministic)
}
func (m *Health) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Health.Merge(m, src)
}
func (m *Health) XXX_Size() int {
	return xxx_messageInfo_Health.Size(m)
}
func (m *Health) XXX_DiscardUnknown() {
	xxx_messageInfo_Health.DiscardUnknown(m)
}

var xxx_messageInfo_Health proto.InternalMessageInfo

func (m *Health) GetStatus() HealthStatus {
	if m != nil {
		return m.Status
	}
	return HealthStatus_HEALTH_UNKNOWN
}

func init() {
	proto.RegisterEnum("v1.model.HealthStatus", HealthStatus_name, HealthStatus_value)
	proto.RegisterType((*Health)(nil), "v1.model.Health")
}

func init() { proto.RegisterFile("protos/model/v1/health.proto", fileDescriptor_a9e68dd7d671de82) }

var fileDescriptor_a9e68dd7d671de82 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0x2f, 0x33, 0xd4, 0xcf, 0x48, 0x4d, 0xcc,
	0x29, 0xc9, 0xd0, 0x03, 0x0b, 0x0b, 0x71, 0x94, 0x19, 0xea, 0x81, 0x65, 0x94, 0x2c, 0xb8, 0xd8,
	0x3c, 0xc0, 0x32, 0x42, 0x7a, 0x5c, 0x6c, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x7c, 0x46, 0x62, 0x7a, 0x30, 0x45, 0x7a, 0x10, 0x15, 0xc1, 0x60, 0xd9, 0x20, 0xa8,
	0x2a, 0xad, 0x04, 0x2e, 0x1e, 0x64, 0x71, 0x21, 0x21, 0x2e, 0x3e, 0x0f, 0x57, 0x47, 0x9f, 0x10,
	0x8f, 0xf8, 0x50, 0x3f, 0x6f, 0x3f, 0xff, 0x70, 0x3f, 0x01, 0x06, 0x21, 0x31, 0x2e, 0x21, 0xa8,
	0x98, 0x7f, 0x80, 0x6b, 0x90, 0x63, 0x88, 0xa7, 0xbf, 0x9f, 0xa3, 0x8f, 0x00, 0x23, 0x92, 0x5a,
	0x7f, 0x37, 0x37, 0x1f, 0x4f, 0x3f, 0x57, 0x01, 0x26, 0x21, 0x01, 0x2e, 0x1e, 0xa8, 0x98, 0x6b,
	0x50, 0x90, 0x7f, 0x90, 0x00, 0xb3, 0x93, 0x76, 0x94, 0x66, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92,
	0x5e, 0x72, 0x7e, 0xae, 0xbe, 0x5b, 0x7e, 0x51, 0x6e, 0x62, 0x5e, 0x89, 0xa7, 0xbf, 0x7e, 0x7a,
	0x6a, 0x1e, 0xd8, 0x1b, 0xfa, 0xe9, 0xf9, 0x20, 0x9f, 0x81, 0xdd, 0x98, 0xc4, 0x06, 0x16, 0x32,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xfa, 0xad, 0x60, 0xf9, 0x00, 0x00, 0x00,
}
