// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/model/v1/navigation.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Location struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26a7b989da652f2, []int{0}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Localization struct {
	Odometry             *Odometry     `protobuf:"bytes,1,opt,name=odometry,proto3" json:"odometry,omitempty"`
	Map                  *Map          `protobuf:"bytes,2,opt,name=map,proto3" json:"map,omitempty"`
	PointClouds          []*PointCloud `protobuf:"bytes,3,rep,name=point_clouds,json=pointClouds,proto3" json:"point_clouds,omitempty"`
	Path                 *Path         `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Goal                 *Goal         `protobuf:"bytes,5,opt,name=goal,proto3" json:"goal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Localization) Reset()         { *m = Localization{} }
func (m *Localization) String() string { return proto.CompactTextString(m) }
func (*Localization) ProtoMessage()    {}
func (*Localization) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26a7b989da652f2, []int{1}
}

func (m *Localization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Localization.Unmarshal(m, b)
}
func (m *Localization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Localization.Marshal(b, m, deterministic)
}
func (m *Localization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Localization.Merge(m, src)
}
func (m *Localization) XXX_Size() int {
	return xxx_messageInfo_Localization.Size(m)
}
func (m *Localization) XXX_DiscardUnknown() {
	xxx_messageInfo_Localization.DiscardUnknown(m)
}

var xxx_messageInfo_Localization proto.InternalMessageInfo

func (m *Localization) GetOdometry() *Odometry {
	if m != nil {
		return m.Odometry
	}
	return nil
}

func (m *Localization) GetMap() *Map {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *Localization) GetPointClouds() []*PointCloud {
	if m != nil {
		return m.PointClouds
	}
	return nil
}

func (m *Localization) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *Localization) GetGoal() *Goal {
	if m != nil {
		return m.Goal
	}
	return nil
}

type Odometry struct {
	Pose                 *Transform `protobuf:"bytes,1,opt,name=pose,proto3" json:"pose,omitempty"`
	Twist                *Twist     `protobuf:"bytes,2,opt,name=twist,proto3" json:"twist,omitempty"`
	WorldToLocal         *Transform `protobuf:"bytes,3,opt,name=world_to_local,json=worldToLocal,proto3" json:"world_to_local,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Odometry) Reset()         { *m = Odometry{} }
func (m *Odometry) String() string { return proto.CompactTextString(m) }
func (*Odometry) ProtoMessage()    {}
func (*Odometry) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26a7b989da652f2, []int{2}
}

func (m *Odometry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Odometry.Unmarshal(m, b)
}
func (m *Odometry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Odometry.Marshal(b, m, deterministic)
}
func (m *Odometry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Odometry.Merge(m, src)
}
func (m *Odometry) XXX_Size() int {
	return xxx_messageInfo_Odometry.Size(m)
}
func (m *Odometry) XXX_DiscardUnknown() {
	xxx_messageInfo_Odometry.DiscardUnknown(m)
}

var xxx_messageInfo_Odometry proto.InternalMessageInfo

func (m *Odometry) GetPose() *Transform {
	if m != nil {
		return m.Pose
	}
	return nil
}

func (m *Odometry) GetTwist() *Twist {
	if m != nil {
		return m.Twist
	}
	return nil
}

func (m *Odometry) GetWorldToLocal() *Transform {
	if m != nil {
		return m.WorldToLocal
	}
	return nil
}

type Map struct {
	Resolution   float64    `protobuf:"fixed64,1,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Width        uint32     `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height       uint32     `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Origin       *Transform `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	WorldToLocal *Transform `protobuf:"bytes,5,opt,name=world_to_local,json=worldToLocal,proto3" json:"world_to_local,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*Map_OccupancyGrid
	//	*Map_Url
	//	*Map_Raw
	Data                 isMap_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Map) Reset()         { *m = Map{} }
func (m *Map) String() string { return proto.CompactTextString(m) }
func (*Map) ProtoMessage()    {}
func (*Map) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26a7b989da652f2, []int{3}
}

func (m *Map) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Map.Unmarshal(m, b)
}
func (m *Map) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Map.Marshal(b, m, deterministic)
}
func (m *Map) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Map.Merge(m, src)
}
func (m *Map) XXX_Size() int {
	return xxx_messageInfo_Map.Size(m)
}
func (m *Map) XXX_DiscardUnknown() {
	xxx_messageInfo_Map.DiscardUnknown(m)
}

var xxx_messageInfo_Map proto.InternalMessageInfo

func (m *Map) GetResolution() float64 {
	if m != nil {
		return m.Resolution
	}
	return 0
}

func (m *Map) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Map) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Map) GetOrigin() *Transform {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *Map) GetWorldToLocal() *Transform {
	if m != nil {
		return m.WorldToLocal
	}
	return nil
}

type isMap_Data interface {
	isMap_Data()
}

type Map_OccupancyGrid struct {
	OccupancyGrid *OccupancyGrid `protobuf:"bytes,6,opt,name=occupancy_grid,json=occupancyGrid,proto3,oneof"`
}

type Map_Url struct {
	Url string `protobuf:"bytes,7,opt,name=url,proto3,oneof"`
}

type Map_Raw struct {
	Raw []byte `protobuf:"bytes,8,opt,name=raw,proto3,oneof"`
}

func (*Map_OccupancyGrid) isMap_Data() {}

func (*Map_Url) isMap_Data() {}

func (*Map_Raw) isMap_Data() {}

func (m *Map) GetData() isMap_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Map) GetOccupancyGrid() *OccupancyGrid {
	if x, ok := m.GetData().(*Map_OccupancyGrid); ok {
		return x.OccupancyGrid
	}
	return nil
}

func (m *Map) GetUrl() string {
	if x, ok := m.GetData().(*Map_Url); ok {
		return x.Url
	}
	return ""
}

func (m *Map) GetRaw() []byte {
	if x, ok := m.GetData().(*Map_Raw); ok {
		return x.Raw
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Map) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Map_OccupancyGrid)(nil),
		(*Map_Url)(nil),
		(*Map_Raw)(nil),
	}
}

type OccupancyGrid struct {
	Data                 []int32  `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OccupancyGrid) Reset()         { *m = OccupancyGrid{} }
func (m *OccupancyGrid) String() string { return proto.CompactTextString(m) }
func (*OccupancyGrid) ProtoMessage()    {}
func (*OccupancyGrid) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26a7b989da652f2, []int{4}
}

func (m *OccupancyGrid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OccupancyGrid.Unmarshal(m, b)
}
func (m *OccupancyGrid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OccupancyGrid.Marshal(b, m, deterministic)
}
func (m *OccupancyGrid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OccupancyGrid.Merge(m, src)
}
func (m *OccupancyGrid) XXX_Size() int {
	return xxx_messageInfo_OccupancyGrid.Size(m)
}
func (m *OccupancyGrid) XXX_DiscardUnknown() {
	xxx_messageInfo_OccupancyGrid.DiscardUnknown(m)
}

var xxx_messageInfo_OccupancyGrid proto.InternalMessageInfo

func (m *OccupancyGrid) GetData() []int32 {
	if m != nil {
		return m.Data
	}
	return nil
}

type Path struct {
	WorldToLocal         *Transform   `protobuf:"bytes,1,opt,name=world_to_local,json=worldToLocal,proto3" json:"world_to_local,omitempty"`
	Poses                []*Transform `protobuf:"bytes,2,rep,name=poses,proto3" json:"poses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26a7b989da652f2, []int{5}
}

func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (m *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(m, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetWorldToLocal() *Transform {
	if m != nil {
		return m.WorldToLocal
	}
	return nil
}

func (m *Path) GetPoses() []*Transform {
	if m != nil {
		return m.Poses
	}
	return nil
}

type Goal struct {
	WorldToLocal         *Transform `protobuf:"bytes,1,opt,name=world_to_local,json=worldToLocal,proto3" json:"world_to_local,omitempty"`
	Pose                 *Transform `protobuf:"bytes,2,opt,name=pose,proto3" json:"pose,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Goal) Reset()         { *m = Goal{} }
func (m *Goal) String() string { return proto.CompactTextString(m) }
func (*Goal) ProtoMessage()    {}
func (*Goal) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26a7b989da652f2, []int{6}
}

func (m *Goal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Goal.Unmarshal(m, b)
}
func (m *Goal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Goal.Marshal(b, m, deterministic)
}
func (m *Goal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Goal.Merge(m, src)
}
func (m *Goal) XXX_Size() int {
	return xxx_messageInfo_Goal.Size(m)
}
func (m *Goal) XXX_DiscardUnknown() {
	xxx_messageInfo_Goal.DiscardUnknown(m)
}

var xxx_messageInfo_Goal proto.InternalMessageInfo

func (m *Goal) GetWorldToLocal() *Transform {
	if m != nil {
		return m.WorldToLocal
	}
	return nil
}

func (m *Goal) GetPose() *Transform {
	if m != nil {
		return m.Pose
	}
	return nil
}

type GoalID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoalID) Reset()         { *m = GoalID{} }
func (m *GoalID) String() string { return proto.CompactTextString(m) }
func (*GoalID) ProtoMessage()    {}
func (*GoalID) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26a7b989da652f2, []int{7}
}

func (m *GoalID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoalID.Unmarshal(m, b)
}
func (m *GoalID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoalID.Marshal(b, m, deterministic)
}
func (m *GoalID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoalID.Merge(m, src)
}
func (m *GoalID) XXX_Size() int {
	return xxx_messageInfo_GoalID.Size(m)
}
func (m *GoalID) XXX_DiscardUnknown() {
	xxx_messageInfo_GoalID.DiscardUnknown(m)
}

var xxx_messageInfo_GoalID proto.InternalMessageInfo

func (m *GoalID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Location)(nil), "v1.model.Location")
	proto.RegisterType((*Localization)(nil), "v1.model.Localization")
	proto.RegisterType((*Odometry)(nil), "v1.model.Odometry")
	proto.RegisterType((*Map)(nil), "v1.model.Map")
	proto.RegisterType((*OccupancyGrid)(nil), "v1.model.OccupancyGrid")
	proto.RegisterType((*Path)(nil), "v1.model.Path")
	proto.RegisterType((*Goal)(nil), "v1.model.Goal")
	proto.RegisterType((*GoalID)(nil), "v1.model.GoalID")
}

func init() { proto.RegisterFile("protos/model/v1/navigation.proto", fileDescriptor_b26a7b989da652f2) }

var fileDescriptor_b26a7b989da652f2 = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0xc7, 0x9b, 0xcd, 0xee, 0xba, 0x3d, 0xfb, 0x21, 0x8c, 0x45, 0xc3, 0x2a, 0x1a, 0x22, 0xe2,
	0x96, 0x42, 0x42, 0xeb, 0x85, 0x78, 0x27, 0xb5, 0xd8, 0x16, 0x2c, 0x95, 0xa1, 0x57, 0xde, 0x2c,
	0xd3, 0x4c, 0x4c, 0x46, 0x26, 0x39, 0x61, 0x32, 0xe9, 0x52, 0xdf, 0xc3, 0xc7, 0xf0, 0x9d, 0x7c,
	0x14, 0x99, 0x49, 0xb6, 0xbb, 0xac, 0x2b, 0x16, 0xbc, 0xdb, 0x39, 0xbf, 0xff, 0xf9, 0x9f, 0x8f,
	0x3d, 0x04, 0xfc, 0x52, 0xa1, 0xc6, 0x2a, 0xca, 0x91, 0x27, 0x32, 0xba, 0x39, 0x8c, 0x0a, 0x76,
	0x23, 0x52, 0xa6, 0x05, 0x16, 0xa1, 0x45, 0x64, 0x70, 0x73, 0x18, 0x5a, 0x3a, 0x9d, 0x6e, 0x6a,
	0x73, 0xa6, 0xb3, 0x46, 0x35, 0x7d, 0xfa, 0x07, 0x4b, 0xb8, 0x60, 0x0d, 0x0c, 0x4e, 0x60, 0xf0,
	0x09, 0x63, 0x6b, 0x4a, 0xa6, 0x30, 0x90, 0x4c, 0x0b, 0x5d, 0xf3, 0xc4, 0x73, 0x7c, 0x67, 0xe6,
	0xd0, 0xbb, 0x37, 0x79, 0x06, 0xbb, 0x12, 0x8b, 0xb4, 0x81, 0x1d, 0x0b, 0x57, 0x81, 0xe0, 0x97,
	0x03, 0x23, 0x63, 0x23, 0xc5, 0xf7, 0xc6, 0x2a, 0x84, 0x01, 0x72, 0xcc, 0x13, 0xad, 0x6e, 0xad,
	0xd5, 0xf0, 0x88, 0x84, 0xcb, 0x66, 0xc3, 0xcb, 0x96, 0xd0, 0x3b, 0x0d, 0x79, 0x01, 0x6e, 0xce,
	0x4a, 0x6b, 0x3c, 0x3c, 0x1a, 0xaf, 0xa4, 0x17, 0xac, 0xa4, 0x86, 0x90, 0xb7, 0x30, 0x2a, 0x51,
	0x14, 0x7a, 0x1e, 0x4b, 0xac, 0x79, 0xe5, 0xb9, 0xbe, 0x3b, 0x1b, 0x1e, 0xed, 0xad, 0x94, 0x9f,
	0x0d, 0xfd, 0x60, 0x20, 0x1d, 0x96, 0x77, 0xbf, 0x2b, 0x12, 0x40, 0xb7, 0x64, 0x3a, 0xf3, 0xba,
	0xd6, 0x7a, 0xb2, 0x96, 0xc0, 0x74, 0x46, 0x2d, 0x33, 0x9a, 0x14, 0x99, 0xf4, 0x7a, 0x9b, 0x9a,
	0x53, 0x64, 0x92, 0x5a, 0x16, 0xfc, 0x70, 0x60, 0xb0, 0x6c, 0x9c, 0xbc, 0x86, 0x6e, 0x89, 0x55,
	0xd2, 0x8e, 0xf6, 0x68, 0x95, 0x70, 0xa5, 0x58, 0x51, 0x7d, 0x45, 0x95, 0x53, 0x2b, 0x20, 0xaf,
	0xa0, 0xa7, 0x17, 0xa2, 0xd2, 0xed, 0x64, 0x0f, 0xd7, 0x94, 0x26, 0x4c, 0x1b, 0x4a, 0xde, 0xc1,
	0x64, 0x81, 0x4a, 0xf2, 0xb9, 0xc6, 0xb9, 0x34, 0x7b, 0xf4, 0xdc, 0xbf, 0x3b, 0x8f, 0xac, 0xf4,
	0x0a, 0xed, 0xc2, 0x83, 0x9f, 0x1d, 0x70, 0x2f, 0x58, 0x49, 0x9e, 0x03, 0xa8, 0xa4, 0x42, 0x59,
	0x9b, 0xfd, 0xb7, 0x7f, 0xdf, 0x5a, 0x84, 0xec, 0x41, 0x6f, 0x21, 0xb8, 0xce, 0x6c, 0x27, 0x63,
	0xda, 0x3c, 0xc8, 0x63, 0xe8, 0x67, 0x89, 0x48, 0x33, 0x6d, 0x0b, 0x8e, 0x69, 0xfb, 0x22, 0x07,
	0xd0, 0x47, 0x25, 0x52, 0x51, 0xb4, 0x7b, 0xdb, 0xda, 0x48, 0x2b, 0xd9, 0xd2, 0x7d, 0xef, 0x9e,
	0xdd, 0x93, 0xf7, 0x30, 0xc1, 0x38, 0xae, 0x4b, 0x56, 0xc4, 0xb7, 0xf3, 0x54, 0x09, 0xee, 0xf5,
	0x6d, 0xea, 0x93, 0xb5, 0x6b, 0x59, 0xf2, 0x53, 0x25, 0xf8, 0xd9, 0x0e, 0x1d, 0xe3, 0x7a, 0x80,
	0x10, 0x70, 0x6b, 0x25, 0xbd, 0x07, 0xbe, 0x33, 0xdb, 0x3d, 0xdb, 0xa1, 0xe6, 0x61, 0x62, 0x8a,
	0x2d, 0xbc, 0x81, 0xef, 0xcc, 0x46, 0x26, 0xa6, 0xd8, 0xe2, 0xb8, 0x0f, 0x5d, 0xce, 0x34, 0x0b,
	0x5e, 0xc2, 0xf8, 0x72, 0xc3, 0xc0, 0x02, 0xcf, 0xf1, 0xdd, 0x59, 0x8f, 0x36, 0x22, 0x09, 0x5d,
	0x73, 0x1e, 0x5b, 0x26, 0x73, 0xee, 0x3b, 0xd9, 0x3e, 0xf4, 0xcc, 0x05, 0x54, 0x5e, 0xc7, 0x5e,
	0xea, 0xd6, 0x8c, 0x46, 0x11, 0x7c, 0x83, 0xae, 0x39, 0xb4, 0xff, 0xa9, 0xb6, 0x3c, 0xc8, 0xce,
	0x3f, 0x0e, 0x32, 0xf0, 0xa0, 0x6f, 0x6a, 0x9d, 0x9f, 0x90, 0x09, 0x74, 0x04, 0xb7, 0x15, 0x76,
	0x69, 0x47, 0xf0, 0xe3, 0x83, 0x2f, 0xfb, 0xa9, 0xd0, 0x59, 0x7d, 0x1d, 0xc6, 0x98, 0x47, 0x1f,
	0x51, 0xe5, 0xac, 0xd0, 0xe7, 0x97, 0x51, 0x9a, 0x14, 0xf6, 0x53, 0x11, 0xa5, 0x68, 0x3f, 0x1e,
	0xc6, 0xf6, 0xba, 0x6f, 0x43, 0x6f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x7b, 0xf3, 0x6c,
	0xa4, 0x04, 0x00, 0x00,
}
