// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/model/v1/ros.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ROSTopicType int32

const (
	ROSTopicType_UNKNOWN                      ROSTopicType = 0
	ROSTopicType_STD_MSGS_BOOL                ROSTopicType = 1
	ROSTopicType_SENSOR_MSGS_COMPRESSED_IMAGE ROSTopicType = 2
	ROSTopicType_STD_MSGS_STRING              ROSTopicType = 3
	ROSTopicType_GEOMETRY_MSGS_POSE           ROSTopicType = 4
	ROSTopicType_ACTIONLIB_MSGS_GOALID        ROSTopicType = 5
	ROSTopicType_GEOMETRY_MSGS_TWIST          ROSTopicType = 6
	ROSTopicType_H264_VIDEO_FRAME             ROSTopicType = 7
	ROSTopicType_AUDIO_CHUNK                  ROSTopicType = 8
	ROSTopicType_STD_MSGS_FLOAT64             ROSTopicType = 9
)

var ROSTopicType_name = map[int32]string{
	0: "UNKNOWN",
	1: "STD_MSGS_BOOL",
	2: "SENSOR_MSGS_COMPRESSED_IMAGE",
	3: "STD_MSGS_STRING",
	4: "GEOMETRY_MSGS_POSE",
	5: "ACTIONLIB_MSGS_GOALID",
	6: "GEOMETRY_MSGS_TWIST",
	7: "H264_VIDEO_FRAME",
	8: "AUDIO_CHUNK",
	9: "STD_MSGS_FLOAT64",
}

var ROSTopicType_value = map[string]int32{
	"UNKNOWN":                      0,
	"STD_MSGS_BOOL":                1,
	"SENSOR_MSGS_COMPRESSED_IMAGE": 2,
	"STD_MSGS_STRING":              3,
	"GEOMETRY_MSGS_POSE":           4,
	"ACTIONLIB_MSGS_GOALID":        5,
	"GEOMETRY_MSGS_TWIST":          6,
	"H264_VIDEO_FRAME":             7,
	"AUDIO_CHUNK":                  8,
	"STD_MSGS_FLOAT64":             9,
}

func (x ROSTopicType) String() string {
	return proto.EnumName(ROSTopicType_name, int32(x))
}

func (ROSTopicType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9010adf44cfe47e0, []int{0}
}

type ROSTopic struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	EncodeVideo          bool     `protobuf:"varint,3,opt,name=encode_video,json=encodeVideo,proto3" json:"encode_video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ROSTopic) Reset()         { *m = ROSTopic{} }
func (m *ROSTopic) String() string { return proto.CompactTextString(m) }
func (*ROSTopic) ProtoMessage()    {}
func (*ROSTopic) Descriptor() ([]byte, []int) {
	return fileDescriptor_9010adf44cfe47e0, []int{0}
}

func (m *ROSTopic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ROSTopic.Unmarshal(m, b)
}
func (m *ROSTopic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ROSTopic.Marshal(b, m, deterministic)
}
func (m *ROSTopic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ROSTopic.Merge(m, src)
}
func (m *ROSTopic) XXX_Size() int {
	return xxx_messageInfo_ROSTopic.Size(m)
}
func (m *ROSTopic) XXX_DiscardUnknown() {
	xxx_messageInfo_ROSTopic.DiscardUnknown(m)
}

var xxx_messageInfo_ROSTopic proto.InternalMessageInfo

func (m *ROSTopic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ROSTopic) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ROSTopic) GetEncodeVideo() bool {
	if m != nil {
		return m.EncodeVideo
	}
	return false
}

type ROSLocalization struct {
	MapTopic             string   `protobuf:"bytes,1,opt,name=map_topic,json=mapTopic,proto3" json:"map_topic,omitempty"`
	OdomTopic            string   `protobuf:"bytes,2,opt,name=odom_topic,json=odomTopic,proto3" json:"odom_topic,omitempty"`
	PointCloudTopics     []string `protobuf:"bytes,3,rep,name=point_cloud_topics,json=pointCloudTopics,proto3" json:"point_cloud_topics,omitempty"`
	PathTopic            string   `protobuf:"bytes,4,opt,name=path_topic,json=pathTopic,proto3" json:"path_topic,omitempty"`
	GoalTopic            string   `protobuf:"bytes,5,opt,name=goal_topic,json=goalTopic,proto3" json:"goal_topic,omitempty"`
	BaseReferenceFrame   string   `protobuf:"bytes,6,opt,name=base_reference_frame,json=baseReferenceFrame,proto3" json:"base_reference_frame,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ROSLocalization) Reset()         { *m = ROSLocalization{} }
func (m *ROSLocalization) String() string { return proto.CompactTextString(m) }
func (*ROSLocalization) ProtoMessage()    {}
func (*ROSLocalization) Descriptor() ([]byte, []int) {
	return fileDescriptor_9010adf44cfe47e0, []int{1}
}

func (m *ROSLocalization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ROSLocalization.Unmarshal(m, b)
}
func (m *ROSLocalization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ROSLocalization.Marshal(b, m, deterministic)
}
func (m *ROSLocalization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ROSLocalization.Merge(m, src)
}
func (m *ROSLocalization) XXX_Size() int {
	return xxx_messageInfo_ROSLocalization.Size(m)
}
func (m *ROSLocalization) XXX_DiscardUnknown() {
	xxx_messageInfo_ROSLocalization.DiscardUnknown(m)
}

var xxx_messageInfo_ROSLocalization proto.InternalMessageInfo

func (m *ROSLocalization) GetMapTopic() string {
	if m != nil {
		return m.MapTopic
	}
	return ""
}

func (m *ROSLocalization) GetOdomTopic() string {
	if m != nil {
		return m.OdomTopic
	}
	return ""
}

func (m *ROSLocalization) GetPointCloudTopics() []string {
	if m != nil {
		return m.PointCloudTopics
	}
	return nil
}

func (m *ROSLocalization) GetPathTopic() string {
	if m != nil {
		return m.PathTopic
	}
	return ""
}

func (m *ROSLocalization) GetGoalTopic() string {
	if m != nil {
		return m.GoalTopic
	}
	return ""
}

func (m *ROSLocalization) GetBaseReferenceFrame() string {
	if m != nil {
		return m.BaseReferenceFrame
	}
	return ""
}

type ROSTransformTree struct {
	BaseReferenceFrame   string   `protobuf:"bytes,1,opt,name=base_reference_frame,json=baseReferenceFrame,proto3" json:"base_reference_frame,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ROSTransformTree) Reset()         { *m = ROSTransformTree{} }
func (m *ROSTransformTree) String() string { return proto.CompactTextString(m) }
func (*ROSTransformTree) ProtoMessage()    {}
func (*ROSTransformTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_9010adf44cfe47e0, []int{2}
}

func (m *ROSTransformTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ROSTransformTree.Unmarshal(m, b)
}
func (m *ROSTransformTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ROSTransformTree.Marshal(b, m, deterministic)
}
func (m *ROSTransformTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ROSTransformTree.Merge(m, src)
}
func (m *ROSTransformTree) XXX_Size() int {
	return xxx_messageInfo_ROSTransformTree.Size(m)
}
func (m *ROSTransformTree) XXX_DiscardUnknown() {
	xxx_messageInfo_ROSTransformTree.DiscardUnknown(m)
}

var xxx_messageInfo_ROSTransformTree proto.InternalMessageInfo

func (m *ROSTransformTree) GetBaseReferenceFrame() string {
	if m != nil {
		return m.BaseReferenceFrame
	}
	return ""
}

type ROSMessageToPublish struct {
	Stream    string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	FrameId   string `protobuf:"bytes,7,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	Timestamp uint64 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*ROSMessageToPublish_Twist
	//	*ROSMessageToPublish_Bool
	//	*ROSMessageToPublish_CompressedImage
	//	*ROSMessageToPublish_Text
	//	*ROSMessageToPublish_Pose
	//	*ROSMessageToPublish_GoalID
	//	*ROSMessageToPublish_Numeric
	Data                 isROSMessageToPublish_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ROSMessageToPublish) Reset()         { *m = ROSMessageToPublish{} }
func (m *ROSMessageToPublish) String() string { return proto.CompactTextString(m) }
func (*ROSMessageToPublish) ProtoMessage()    {}
func (*ROSMessageToPublish) Descriptor() ([]byte, []int) {
	return fileDescriptor_9010adf44cfe47e0, []int{3}
}

func (m *ROSMessageToPublish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ROSMessageToPublish.Unmarshal(m, b)
}
func (m *ROSMessageToPublish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ROSMessageToPublish.Marshal(b, m, deterministic)
}
func (m *ROSMessageToPublish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ROSMessageToPublish.Merge(m, src)
}
func (m *ROSMessageToPublish) XXX_Size() int {
	return xxx_messageInfo_ROSMessageToPublish.Size(m)
}
func (m *ROSMessageToPublish) XXX_DiscardUnknown() {
	xxx_messageInfo_ROSMessageToPublish.DiscardUnknown(m)
}

var xxx_messageInfo_ROSMessageToPublish proto.InternalMessageInfo

func (m *ROSMessageToPublish) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

func (m *ROSMessageToPublish) GetFrameId() string {
	if m != nil {
		return m.FrameId
	}
	return ""
}

func (m *ROSMessageToPublish) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type isROSMessageToPublish_Data interface {
	isROSMessageToPublish_Data()
}

type ROSMessageToPublish_Twist struct {
	Twist *Twist `protobuf:"bytes,2,opt,name=twist,proto3,oneof"`
}

type ROSMessageToPublish_Bool struct {
	Bool bool `protobuf:"varint,3,opt,name=bool,proto3,oneof"`
}

type ROSMessageToPublish_CompressedImage struct {
	CompressedImage []byte `protobuf:"bytes,4,opt,name=compressed_image,json=compressedImage,proto3,oneof"`
}

type ROSMessageToPublish_Text struct {
	Text string `protobuf:"bytes,5,opt,name=text,proto3,oneof"`
}

type ROSMessageToPublish_Pose struct {
	Pose *Transform `protobuf:"bytes,6,opt,name=pose,proto3,oneof"`
}

type ROSMessageToPublish_GoalID struct {
	GoalID *GoalID `protobuf:"bytes,9,opt,name=goalID,proto3,oneof"`
}

type ROSMessageToPublish_Numeric struct {
	Numeric *Numeric `protobuf:"bytes,10,opt,name=numeric,proto3,oneof"`
}

func (*ROSMessageToPublish_Twist) isROSMessageToPublish_Data() {}

func (*ROSMessageToPublish_Bool) isROSMessageToPublish_Data() {}

func (*ROSMessageToPublish_CompressedImage) isROSMessageToPublish_Data() {}

func (*ROSMessageToPublish_Text) isROSMessageToPublish_Data() {}

func (*ROSMessageToPublish_Pose) isROSMessageToPublish_Data() {}

func (*ROSMessageToPublish_GoalID) isROSMessageToPublish_Data() {}

func (*ROSMessageToPublish_Numeric) isROSMessageToPublish_Data() {}

func (m *ROSMessageToPublish) GetData() isROSMessageToPublish_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ROSMessageToPublish) GetTwist() *Twist {
	if x, ok := m.GetData().(*ROSMessageToPublish_Twist); ok {
		return x.Twist
	}
	return nil
}

func (m *ROSMessageToPublish) GetBool() bool {
	if x, ok := m.GetData().(*ROSMessageToPublish_Bool); ok {
		return x.Bool
	}
	return false
}

func (m *ROSMessageToPublish) GetCompressedImage() []byte {
	if x, ok := m.GetData().(*ROSMessageToPublish_CompressedImage); ok {
		return x.CompressedImage
	}
	return nil
}

func (m *ROSMessageToPublish) GetText() string {
	if x, ok := m.GetData().(*ROSMessageToPublish_Text); ok {
		return x.Text
	}
	return ""
}

func (m *ROSMessageToPublish) GetPose() *Transform {
	if x, ok := m.GetData().(*ROSMessageToPublish_Pose); ok {
		return x.Pose
	}
	return nil
}

func (m *ROSMessageToPublish) GetGoalID() *GoalID {
	if x, ok := m.GetData().(*ROSMessageToPublish_GoalID); ok {
		return x.GoalID
	}
	return nil
}

func (m *ROSMessageToPublish) GetNumeric() *Numeric {
	if x, ok := m.GetData().(*ROSMessageToPublish_Numeric); ok {
		return x.Numeric
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ROSMessageToPublish) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ROSMessageToPublish_Twist)(nil),
		(*ROSMessageToPublish_Bool)(nil),
		(*ROSMessageToPublish_CompressedImage)(nil),
		(*ROSMessageToPublish_Text)(nil),
		(*ROSMessageToPublish_Pose)(nil),
		(*ROSMessageToPublish_GoalID)(nil),
		(*ROSMessageToPublish_Numeric)(nil),
	}
}

func init() {
	proto.RegisterEnum("v1.model.ROSTopicType", ROSTopicType_name, ROSTopicType_value)
	proto.RegisterType((*ROSTopic)(nil), "v1.model.ROSTopic")
	proto.RegisterType((*ROSLocalization)(nil), "v1.model.ROSLocalization")
	proto.RegisterType((*ROSTransformTree)(nil), "v1.model.ROSTransformTree")
	proto.RegisterType((*ROSMessageToPublish)(nil), "v1.model.ROSMessageToPublish")
}

func init() { proto.RegisterFile("protos/model/v1/ros.proto", fileDescriptor_9010adf44cfe47e0) }

var fileDescriptor_9010adf44cfe47e0 = []byte{
	// 708 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xdb, 0x6f, 0xe2, 0x46,
	0x18, 0xc5, 0x71, 0x20, 0x5c, 0x3e, 0x52, 0xe1, 0x1d, 0xd2, 0xad, 0x93, 0x6e, 0x25, 0x9a, 0x97,
	0xb2, 0xbb, 0x2d, 0x74, 0xd3, 0xd5, 0xbe, 0x73, 0x31, 0x60, 0x2d, 0x78, 0xa2, 0xb1, 0x49, 0xd4,
	0xbe, 0x58, 0x83, 0x3d, 0x01, 0x4b, 0xd8, 0x63, 0xd9, 0x03, 0xbd, 0xfc, 0xcb, 0x95, 0xfa, 0xd8,
	0xe7, 0x6a, 0x66, 0x20, 0x74, 0x23, 0xe5, 0xcd, 0xdf, 0xf9, 0x9d, 0x39, 0xdf, 0xe8, 0x18, 0x0c,
	0x57, 0x59, 0xce, 0x05, 0x2f, 0xfa, 0x09, 0x8f, 0xd8, 0xb6, 0xbf, 0xff, 0xd0, 0xcf, 0x79, 0xd1,
	0x53, 0x1a, 0xaa, 0xef, 0x3f, 0xf4, 0x94, 0x7c, 0x7d, 0xfd, 0xdc, 0x94, 0x50, 0xb1, 0xd1, 0xae,
	0xeb, 0xce, 0x73, 0x96, 0xd2, 0x7d, 0xbc, 0xa6, 0x22, 0xe6, 0xa9, 0x76, 0xdc, 0x2c, 0xa1, 0x4e,
	0xb0, 0xe7, 0xf3, 0x2c, 0x0e, 0x11, 0x82, 0x4a, 0x4a, 0x13, 0x66, 0x19, 0x1d, 0xa3, 0xdb, 0x20,
	0xea, 0x59, 0x6a, 0x19, 0x15, 0x1b, 0xeb, 0x4c, 0x6b, 0xf2, 0x19, 0x7d, 0x0f, 0x17, 0x2c, 0x0d,
	0x79, 0xc4, 0x82, 0x7d, 0x1c, 0x31, 0x6e, 0x95, 0x3b, 0x46, 0xb7, 0x4e, 0x9a, 0x5a, 0xbb, 0x97,
	0xd2, 0xcd, 0xdf, 0x06, 0xb4, 0x08, 0xf6, 0xe6, 0x3c, 0xa4, 0xdb, 0xf8, 0x2f, 0xb5, 0x10, 0x7d,
	0x0b, 0x8d, 0x84, 0x66, 0x81, 0x90, 0xbb, 0x0e, 0x3b, 0xea, 0x09, 0xcd, 0xf4, 0xee, 0xef, 0x00,
	0x78, 0xc4, 0x93, 0x03, 0xd5, 0xdb, 0x1a, 0x52, 0xd1, 0xf8, 0x47, 0x40, 0x19, 0x8f, 0x53, 0x11,
	0x84, 0x5b, 0xbe, 0x8b, 0xb4, 0xab, 0xb0, 0xca, 0x9d, 0x72, 0xb7, 0x41, 0x4c, 0x45, 0x46, 0x12,
	0x28, 0x73, 0x21, 0xc3, 0xe4, 0x45, 0x0f, 0x61, 0x15, 0x1d, 0x26, 0x95, 0xa7, 0x5d, 0x6b, 0x4e,
	0xb7, 0x07, 0x7c, 0xae, 0xb1, 0x54, 0x34, 0xfe, 0x19, 0x2e, 0x57, 0xb4, 0x60, 0x41, 0xce, 0x1e,
	0x59, 0xce, 0xd2, 0x90, 0x05, 0x8f, 0xb9, 0xac, 0xa5, 0xaa, 0x8c, 0x48, 0x32, 0x72, 0x44, 0x13,
	0x49, 0x6e, 0xc6, 0x60, 0xca, 0x12, 0x73, 0x9a, 0x16, 0x8f, 0x3c, 0x4f, 0xfc, 0x9c, 0xb1, 0x17,
	0x53, 0x8c, 0x17, 0x53, 0xfe, 0x3d, 0x83, 0x36, 0xc1, 0xde, 0x82, 0x15, 0x05, 0x5d, 0x33, 0x9f,
	0xdf, 0xed, 0x56, 0xdb, 0xb8, 0xd8, 0xa0, 0xd7, 0x50, 0x2d, 0x44, 0xce, 0x68, 0x72, 0x38, 0x7b,
	0x98, 0xd0, 0x15, 0xd4, 0x55, 0x64, 0x10, 0x47, 0x56, 0x4d, 0x91, 0x9a, 0x9a, 0x9d, 0x08, 0xbd,
	0x81, 0x86, 0x88, 0x13, 0x56, 0x08, 0x9a, 0x64, 0x56, 0xbd, 0x63, 0x74, 0x2b, 0xe4, 0x24, 0xa0,
	0x1f, 0xe0, 0x5c, 0xfc, 0x1e, 0x17, 0x42, 0xd5, 0xdc, 0xbc, 0x6d, 0xf5, 0x8e, 0xbf, 0xa5, 0x9e,
	0x2f, 0xe5, 0x59, 0x89, 0x68, 0x8e, 0x2e, 0xa1, 0xb2, 0xe2, 0x7c, 0xab, 0x5f, 0xf0, 0xac, 0x44,
	0xd4, 0x84, 0xde, 0x83, 0x19, 0xf2, 0x24, 0xcb, 0x59, 0x51, 0xb0, 0x28, 0x88, 0x13, 0xba, 0x66,
	0xaa, 0xe3, 0x8b, 0x59, 0x89, 0xb4, 0x4e, 0xc4, 0x91, 0x40, 0x46, 0x08, 0xf6, 0x87, 0xd0, 0x2d,
	0xcb, 0x08, 0x39, 0xa1, 0xb7, 0x50, 0xc9, 0x78, 0xa1, 0x2b, 0x6d, 0xde, 0xb6, 0xff, 0x77, 0x81,
	0x63, 0x87, 0xd2, 0x2a, 0x2d, 0xe8, 0x1d, 0x54, 0xe5, 0xab, 0x71, 0xc6, 0x56, 0x43, 0x99, 0xcd,
	0x93, 0x79, 0xaa, 0xf4, 0x59, 0x89, 0x1c, 0x1c, 0xe8, 0x27, 0xa8, 0xa5, 0xbb, 0x84, 0xe5, 0x71,
	0x68, 0x81, 0x32, 0xbf, 0x3a, 0x99, 0x5d, 0x0d, 0x66, 0x25, 0x72, 0xf4, 0x0c, 0xab, 0x50, 0x89,
	0xa8, 0xa0, 0xef, 0xfe, 0x31, 0xe0, 0xe2, 0xf8, 0x27, 0xf0, 0xff, 0xcc, 0x18, 0x6a, 0x42, 0x6d,
	0xe9, 0x7e, 0x76, 0xf1, 0x83, 0x6b, 0x96, 0xd0, 0x2b, 0xf8, 0xca, 0xf3, 0xc7, 0xc1, 0xc2, 0x9b,
	0x7a, 0xc1, 0x10, 0xe3, 0xb9, 0x69, 0xa0, 0x0e, 0xbc, 0xf1, 0x6c, 0xd7, 0xc3, 0x44, 0xab, 0x23,
	0xbc, 0xb8, 0x23, 0xb6, 0xe7, 0xd9, 0xe3, 0xc0, 0x59, 0x0c, 0xa6, 0xb6, 0x79, 0x86, 0xda, 0xd0,
	0x7a, 0x3a, 0xe4, 0xf9, 0xc4, 0x71, 0xa7, 0x66, 0x19, 0xbd, 0x06, 0x34, 0xb5, 0xf1, 0xc2, 0xf6,
	0xc9, 0xaf, 0x9a, 0xdc, 0x61, 0xcf, 0x36, 0x2b, 0xe8, 0x0a, 0xbe, 0x1e, 0x8c, 0x7c, 0x07, 0xbb,
	0x73, 0x67, 0xa8, 0xc1, 0x14, 0x0f, 0xe6, 0xce, 0xd8, 0x3c, 0x47, 0xdf, 0x40, 0xfb, 0xcb, 0x23,
	0xfe, 0x83, 0xe3, 0xf9, 0x66, 0x15, 0x5d, 0x82, 0x39, 0xbb, 0xfd, 0xf4, 0x31, 0xb8, 0x77, 0xc6,
	0x36, 0x0e, 0x26, 0x64, 0xb0, 0xb0, 0xcd, 0x1a, 0x6a, 0x41, 0x73, 0xb0, 0x1c, 0x3b, 0x38, 0x18,
	0xcd, 0x96, 0xee, 0x67, 0xb3, 0x2e, 0x6d, 0x4f, 0xf7, 0x98, 0xcc, 0xf1, 0xc0, 0xff, 0xf4, 0xd1,
	0x6c, 0x0c, 0xdf, 0xff, 0xf6, 0x76, 0x1d, 0x8b, 0xcd, 0x6e, 0xd5, 0x0b, 0x79, 0xd2, 0x9f, 0xf0,
	0x3c, 0xa1, 0xa9, 0x70, 0x70, 0x7f, 0xcd, 0x52, 0xf5, 0x55, 0xe8, 0xaf, 0xb9, 0xfa, 0x90, 0xc8,
	0xe2, 0x56, 0x55, 0x25, 0xfd, 0xf2, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x5a, 0x17, 0x11,
	0x8d, 0x04, 0x00, 0x00,
}
